import type { Metadata } from "next";
import Link from "next/link";
import { getWebsitePageByPath, metadataFromWebsitePage } from "@/lib/website-pages";

export async function generateMetadata():Promise<Metadata>{return metadataFromWebsitePage(await getWebsitePageByPath("/why-buy-from-yesmoto"),{title:"Why Buy From YesMoto",description:"Carefully selected motorcycles, honest presentation, nationwide delivery and over 22 years of motorcycle experience.",path:"/why-buy-from-yesmoto"})}
const reasons=["Over 22 years of motorcycle industry experience","Family-run independent business","No routine auction buying","Carefully selected motorcycles and scooters","Professional workshop preparation","Detailed photography and walkaround videos","Nationwide delivery","Finance available","Warranty included","Honest descriptions","No pressure sales","Friendly, knowledgeable service"];
const services=[{title:"Carefully selected",copy:"Sourced from private owners, franchised dealer part exchanges and Sell Your Motorbike Ltd—not routinely from auction."},{title:"Professionally prepared",copy:"Condition-led preparation, structured PDI, history checks, at least six months MOT and professional valeting."},{title:"Buy online confidently",copy:"50–100 photographs, walkaround video, detailed descriptions and honest presentation of each motorcycle."},{title:"Delivered nationwide",copy:"Specialist transport partners deliver throughout mainland UK with a personal handover on arrival."},{title:"Flexible finance",copy:"HP and PCP may be available through Jigsaw Finance, subject to status and lender criteria."},{title:"Warranty included",copy:"Qualifying motorcycles include a 3-month Warranty First warranty, with extended cover available."}];

export default function WhyBuy(){return <>
  <section className="info-hero why-hero"><div className="wide"><p>THE YESMOTO DIFFERENCE</p><h1>BUYING USED<br/><em>SHOULD BE SIMPLE.</em></h1><h2>Transparent information, proper preparation and personal service.</h2><div><Link href="/used-bikes">Find your motorcycle</Link><Link href="/about" className="outline">Meet YesMoto</Link></div></div></section>
  <section className="info-proof wide"><article><strong>22+</strong><span>Years of experience</span></article><article><strong>90%</strong><span>Customers buying remotely</span></article><article><strong>Independent</strong><span>Family-run business</span></article><article><strong>Nationwide</strong><span>UK motorcycle delivery</span></article></section>
  <section className="info-intro wide"><div><p className="about-kicker">INFORMED, NEVER PRESSURED</p><h2>A BETTER WAY TO BUY YOUR NEXT BIKE.</h2></div><div><p>Whether you’re buying your first scooter or your next adventure motorcycle, our aim is to give you everything needed to make the right decision.</p><p>Our knowledge was built hands-on—from apprentice technician and workshop management to motorcycle buying and dealership management. That experience shapes how every YesMoto motorcycle is selected, prepared and presented.</p></div></section>
  <section className="reasons-grid wide">{services.map((item,index)=><article key={item.title}><span>{String(index+1).padStart(2,"0")}</span><h2>{item.title}</h2><p>{item.copy}</p></article>)}</section>
  <section className="trust-list"><div className="wide"><div><p className="about-kicker">WHY RIDERS CHOOSE YESMOTO</p><h2>EVERYTHING WE’D EXPECT AS A CUSTOMER.</h2><p>We’re real people who know motorcycles. There’s no pressure selling—only honest advice about whether a motorcycle is right for you.</p></div><div>{reasons.map(reason=><span key={reason}>{reason}</span>)}</div></div></section>
  <section className="info-cta"><div className="wide"><p>LOOKING FOR YOUR NEXT MOTORCYCLE?</p><h2>LET’S FIND THE RIGHT BIKE.</h2><div><Link href="/used-bikes">Browse latest stock</Link><Link href="/contact" className="outline">Talk to our team</Link></div></div></section>
  </>}
