import type { Metadata } from "next";
import Link from "next/link";

export const metadata:Metadata={title:"Motorcycle Preparation",description:"Discover how every used motorcycle at YesMoto is inspected, prepared and presented before sale."};
const preparation=["Servicing","Replacement tyres","Brake maintenance","General repairs","Replacement parts where required","Safety checks","Road testing where appropriate","Professional valeting"];
const pdi=["Controls","Brakes","Suspension","Steering","Tyres","Electrical systems","Fluid levels","Drive system","General safety items","Final inspection"];
const history=["Outstanding finance","Insurance write-off status","Stolen register","Mileage history","VIN confirmation","Engine number","MOT history","Vehicle specification"];

export default function MotorcyclePreparation(){return <>
  <section className="info-hero preparation-hero"><div className="wide"><p>THE YESMOTO WORKSHOP</p><h1>PREPARED<br/><em>WITH CARE.</em></h1><h2>Individually assessed. Professionally prepared. Ready to enjoy.</h2><div><Link href="/used-bikes">Browse prepared bikes</Link><Link href="/contact" className="outline">Ask our team</Link></div></div></section>
  <section className="info-proof wide"><article><strong>Individual</strong><span>Condition-based preparation</span></article><article><strong>22+ years</strong><span>Motorcycle experience</span></article><article><strong>6 months</strong><span>Minimum MOT</span></article><article><strong>100%</strong><span>History checked</span></article></section>
  <section className="info-intro wide"><div><p className="about-kicker">NO ONE-SIZE-FITS-ALL CHECKLIST</p><h2>EVERY MOTORCYCLE GETS WHAT IT NEEDS.</h2></div><div><p>Every motorcycle and scooter at YesMoto is individually assessed according to its condition, mileage, age and service history before preparation begins.</p><p>Our aim is simple: to supply motorcycles that are safe, well presented and ready to be enjoyed. We use genuine manufacturer parts where appropriate and trusted quality aftermarket parts when suitable.</p></div></section>
  <section className="checklist-feature"><div className="wide"><div><p className="about-kicker">INDIVIDUAL PREPARATION</p><h2>WORK TAILORED TO THE MOTORCYCLE.</h2><p>Preparation varies depending on what each bike genuinely requires.</p></div><div className="check-grid">{preparation.map(item=><span key={item}>{item}</span>)}</div></div></section>
  <section className="inspection-section wide"><div><p className="about-kicker">PRE-DELIVERY INSPECTION</p><h2>A STRUCTURED FINAL CHECK.</h2><p>Before collection or delivery, every retail motorcycle receives a PDI covering its key safety and operating components.</p></div><div className="inspection-grid">{pdi.map((item,index)=><div key={item}><span>{String(index+1).padStart(2,"0")}</span><b>{item}</b></div>)}</div></section>
  <section className="split-info wide"><article><p className="about-kicker">MINIMUM 6 MONTHS MOT</p><h2>READY FOR THE ROAD.</h2><p>Every retail motorcycle is supplied with at least six months MOT. Where less remains at preparation, a fresh MOT is completed before sale where appropriate.</p></article><article className="accent-card"><p className="about-kicker">VEHICLE HISTORY CHECKS</p><h2>CONFIDENCE BEYOND THE WORKSHOP.</h2><ul>{history.map(item=><li key={item}>{item}</li>)}</ul></article></section>
  <section className="workshop-story"><div className="wide"><div className="workshop-photo"/><div><p className="about-kicker">DEDICATED WORKSHOP</p><h2>FOCUSED SOLELY ON YESMOTO STOCK.</h2><p>With more than 22 years of motorcycle industry experience, we understand why careful preparation matters. Our workshop does not service or repair motorcycles for the general public, allowing us to focus entirely on our own retail stock.</p><p>Preparation is only part of the process. Most adverts include 50–100 professional photographs, a walkaround video and honest details of service history, keys, accessories, documentation and visible cosmetic marks.</p></div></div></section>
  <section className="info-cta"><div className="wide"><p>BUY WITH CONFIDENCE</p><h2>CAREFULLY PREPARED. HONESTLY PRESENTED.</h2><div><Link href="/used-bikes">Browse motorcycles</Link><Link href="/contact" className="outline">Ask about a bike</Link></div></div></section>
  </>}
