"use client";import {useState} from "react";import type {DealerSettings} from "@/lib/dealer-settings";
const groups:[string,string,(keyof DealerSettings)[]][]=[
 ["Business details","Used on invoices, correspondence and dealership documents.",["business_name","trading_name","legal_name","company_number","vat_number","phone","email","website","opening_hours"]],
 ["Business address","The registered/trading address printed on invoices.",["address_line_1","address_line_2","town","county","postcode","country"]],
 ["Invoice settings","Numbering, payment terms, footer and VAT presentation.",["invoice_prefix","invoice_title","payment_terms_days","invoice_footer","vat_wording","payment_instructions","reservation_amount","default_delivery_charge"]],
 ["Bank details","Stored securely in Supabase and printed on customer invoices.",["bank_account_name","bank_sort_code","bank_account_number","payment_reference_prefix"]],
 ["Invoice email template","Editable content. RESEND_API_KEY remains in Vercel.",["email_from_name","email_from_address","email_reply_to","invoice_email_subject","invoice_email_template"]],
 ["Website contact details","Customer-facing contact values for the public website.",["website_contact_phone","website_contact_email","website_whatsapp","whatsapp_number"]]
];
const labels:Partial<Record<keyof DealerSettings,string>>={business_name:"Business name",trading_name:"Trading name",legal_name:"Legal name",address_line_1:"Address line 1",address_line_2:"Address line 2",town:"Town / city",county:"County",postcode:"Postcode",country:"Country",phone:"Business phone",email:"Business email",website:"Website",whatsapp_number:"WhatsApp number",opening_hours:"Opening hours",company_number:"Company number",vat_number:"VAT number",invoice_prefix:"Invoice number prefix",invoice_title:"Invoice title",invoice_footer:"Invoice footer",payment_terms_days:"Payment terms (days)",payment_instructions:"Additional payment instructions",vat_wording:"VAT wording",bank_account_name:"Bank account name",bank_sort_code:"Sort code",bank_account_number:"Account number",payment_reference_prefix:"Payment reference prefix",reservation_amount:"Default reservation amount",default_delivery_charge:"Default delivery charge",email_from_name:"Email sender name",email_from_address:"Email sender address",email_reply_to:"Reply-to address",invoice_email_subject:"Invoice email subject",invoice_email_template:"Invoice email body",website_contact_phone:"Website phone",website_contact_email:"Website email",website_whatsapp:"Website WhatsApp"};
const areas=new Set<keyof DealerSettings>(["invoice_footer","vat_wording","payment_instructions","invoice_email_template"]),numbers=new Set<keyof DealerSettings>(["payment_terms_days","reservation_amount","default_delivery_charge"]);
export function DealerSettingsForm({initial,resendConfigured}:{initial:DealerSettings;resendConfigured:boolean}){const [settings,setSettings]=useState(initial),[busy,setBusy]=useState(false),[message,setMessage]=useState(""),[error,setError]=useState("");const set=(key:keyof DealerSettings,value:string)=>setSettings(current=>({...current,[key]:numbers.has(key)?Number(value):value}));async function save(e:React.FormEvent){e.preventDefault();setBusy(true);setError("");setMessage("");const response=await fetch("/api/crm/settings",{method:"PATCH",headers:{"Content-Type":"application/json"},body:JSON.stringify(settings)}),body=await response.json();if(response.ok){setSettings(body.settings);setMessage("Settings saved.")}else setError(body.error||"Unable to save settings.");setBusy(false)}return <form className="settings dealer-settings" onSubmit={save}><div className={`settings-provider ${resendConfigured?"configured":"missing"}`}><b>Invoice email provider</b><span>{resendConfigured?"Resend is configured in Vercel.":"RESEND_API_KEY is not configured. Invoice emails will not send."}</span></div>{groups.map(([title,sub,fields])=><section key={title}><header><h2>{title}</h2><p>{sub}</p></header><div>{fields.map(key=><label className={areas.has(key)?"full":""} key={key}>{labels[key]??key}{areas.has(key)?<textarea rows={key==="invoice_email_template"?10:4} value={String(settings[key]??"")} onChange={e=>set(key,e.target.value)}/>:<input type={numbers.has(key)?"number":key.includes("email")?"email":"text"} min={numbers.has(key)?0:undefined} step={key==="payment_terms_days"?1:numbers.has(key)?"0.01":undefined} value={String(settings[key]??"")} onChange={e=>set(key,e.target.value)}/>}</label>)}</div>{title==="Invoice email template"&&<p className="settings-tokens">Available placeholders: {'{customer_name}'}, {'{bike}'}, {'{invoice_number}'}, {'{balance}'}, {'{payment_reference}'}, {'{phone}'}, {'{email}'}</p>}</section>)}{message&&<p className="invoice-success">{message}</p>}{error&&<p className="invoice-error">{error}</p>}<div className="settings-save"><button className="admin-primary" disabled={busy}>{busy?"Saving settings...":"Save all settings"}</button></div></form>}
