"use client";
import { FormEvent, useState } from "react";
import { useRouter } from "next/navigation";

export function SaleEditor({ sale }: { sale: Record<string, any> }) {
  const router = useRouter(); const delivery = Array.isArray(sale.delivery) ? sale.delivery[0] : sale.delivery;
  const [saving, setSaving] = useState(false), [message, setMessage] = useState("");
  async function save(event: FormEvent<HTMLFormElement>) { event.preventDefault(); setSaving(true); setMessage(""); const form = new FormData(event.currentTarget); const data = Object.fromEntries(form); event.currentTarget.querySelectorAll<HTMLInputElement>('input[type="checkbox"]').forEach(input => data[input.name] = String(input.checked)); const response = await fetch(`/api/crm/sales/${sale.id}`, { method: "PATCH", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ ...data, ...Object.fromEntries(Object.entries(data).map(([key,value]) => [key, value === "true" ? true : value === "false" ? false : value])) }) }); const result = await response.json() as { error?: string }; setSaving(false); setMessage(response.ok ? "Sale details saved." : result.error || "Unable to save sale."); if (response.ok) router.refresh(); }
  async function undo() { const reason = window.prompt("Why is this sale being reversed?"); if (!reason || !window.confirm("Undo this sale and return the motorcycle to In Stock? Existing financial records will be retained for audit.")) return; setSaving(true); const response = await fetch(`/api/crm/sales/${sale.id}`, { method: "DELETE", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ reason }) }); const result = await response.json() as { error?: string }; setSaving(false); if (!response.ok) { setMessage(result.error || "Unable to undo sale."); return; } router.refresh(); }
  return <form className="stock-editor-panel crm-form sale-editor" onSubmit={save}><div className="stock-form-grid">
    <label><span>Invoice</span><input value={sale.invoice_number ?? ""} readOnly /></label><label><span>Status</span><input value={sale.status ?? ""} readOnly /></label>
    <label><span>Sale price</span><input name="sale_price" type="number" step="0.01" defaultValue={sale.sale_price ?? 0} /></label><label><span>Deposit</span><input name="deposit_amount" type="number" step="0.01" defaultValue={sale.deposit_amount ?? 0} /></label><label><span>Part exchange allowance</span><input name="part_exchange_amount" type="number" step="0.01" defaultValue={sale.part_exchange_amount ?? 0} /></label><label><span>Payment status</span><select name="payment_status" defaultValue={sale.payment_status ?? "Unpaid"}>{["Unpaid","Part Paid","Paid","Refund Required"].map(value => <option key={value}>{value}</option>)}</select></label>
    <label><span>Delivery method</span><select name="delivery_delivery_method" defaultValue={delivery?.delivery_method ?? "Collection"}><option>Collection</option><option>Nationwide Delivery</option></select></label><label><span>Scheduled delivery</span><input name="delivery_scheduled_at" type="datetime-local" defaultValue={delivery?.scheduled_at?.slice(0,16) ?? ""} /></label>
    <label className="full"><span>Sale notes</span><textarea name="notes" rows={4} defaultValue={sale.notes ?? ""} /></label><label className="full"><span>Delivery notes</span><textarea name="delivery_notes" rows={4} defaultValue={delivery?.notes ?? ""} /></label>
    <div className="full delivery-checks">{[["identity_checked","Identity checked"],["licence_verified","Licence verified"],["v5_prepared","V5 prepared"],["handover_completed","Handover completed"],["keys_given","Keys given"],["documents_signed","Documents signed"],["photos_taken","Photos taken"],["hpi_complete","HPI complete"]].map(([key,label]) => <label key={key}><input type="checkbox" name={key} defaultChecked={Boolean(delivery?.[key])} />{label}</label>)}</div>
  </div>{message && <p className="stock-save-message">{message}</p>}<div className="sale-editor-actions"><button type="button" className="danger-action" onClick={undo} disabled={saving || sale.status === "Cancelled"}>Undo sale</button><button className="admin-primary" disabled={saving}>{saving ? "Saving…" : "Save sale details"}</button></div></form>;
}
