import "server-only";

export interface AddressSuggestion {id:string;label:string}
export interface DealerAddress {buildingNumber:string;buildingName:string;addressLine1:string;addressLine2:string;addressLine3:string;town:string;county:string;postcode:string;country:string;latitude:number|null;longitude:number|null;formattedAddress:string[]}
export class AddressServiceError extends Error {constructor(message:string,public status=500){super(message)}}
const cache=new Map<string,{expires:number;value:unknown}>();const ttl=10*60*1000;
const config=()=>{const apiKey=process.env.GETADDRESS_API_KEY,baseUrl=(process.env.GETADDRESS_BASE_URL||"https://api.getAddress.io").replace(/\/$/,"");if(!apiKey)throw new AddressServiceError("Address lookup is not configured.",503);return {apiKey,baseUrl}};
const clean=(value:unknown)=>typeof value==="string"?value.trim():"";const number=(value:unknown)=>{const parsed=Number(value);return Number.isFinite(parsed)?parsed:null};
async function request<T>(path:string,cacheKey:string):Promise<T>{const existing=cache.get(cacheKey);if(existing&&existing.expires>Date.now())return existing.value as T;const {apiKey,baseUrl}=config();let response:Response;try{response=await fetch(`${baseUrl}${path}${path.includes("?")?"&":"?"}api-key=${encodeURIComponent(apiKey)}`,{cache:"no-store",signal:AbortSignal.timeout(8000)})}catch(error){throw new AddressServiceError(error instanceof Error&&error.name==="TimeoutError"?"Address lookup timed out. Please try again.":"Address lookup is temporarily unavailable.",503)}if(response.status===429)throw new AddressServiceError("Address lookup limit reached. Please wait a moment or enter the address manually.",429);if(response.status===404)throw new AddressServiceError("No matching address was found.",404);if(!response.ok)throw new AddressServiceError("Address lookup is temporarily unavailable.",response.status);const value=await response.json() as T;cache.set(cacheKey,{expires:Date.now()+ttl,value});return value}
export async function searchAddresses(term:string):Promise<AddressSuggestion[]>{const query=clean(term).slice(0,160);if(query.length<2)return [];const result=await request<{suggestions?:Array<{id?:unknown;address?:unknown}>}>(`/autocomplete/${encodeURIComponent(query)}?top=12&show-postcode=true`,`search:${query.toLowerCase()}`);return (result.suggestions??[]).map(item=>({id:clean(item.id),label:clean(item.address)})).filter(item=>item.id&&item.label)}
export async function getAddress(id:string):Promise<DealerAddress>{const safe=clean(id).replace(/[^a-zA-Z0-9_\-]/g,"");if(!safe)throw new AddressServiceError("Invalid address selection.",400);const item=await request<Record<string,unknown>>(`/get/${encodeURIComponent(safe)}`,`address:${safe}`);const formatted=Array.isArray(item.formatted_address)?item.formatted_address.map(clean).filter(Boolean):[];return {buildingNumber:clean(item.building_number),buildingName:clean(item.building_name),addressLine1:clean(item.line_1)||formatted[0]||"",addressLine2:clean(item.line_2)||formatted[1]||"",addressLine3:clean(item.line_3)||formatted[2]||"",town:clean(item.town_or_city)||clean(item.locality),county:clean(item.county),postcode:clean(item.postcode).toUpperCase(),country:clean(item.country)||"United Kingdom",latitude:number(item.latitude),longitude:number(item.longitude),formattedAddress:formatted}}
export async function geocode(address:string):Promise<DealerAddress>{const suggestions=await searchAddresses(address);if(!suggestions[0])throw new AddressServiceError("No matching address was found.",404);return getAddress(suggestions[0].id)}
export async function reverseGeocode(latitude:number,longitude:number):Promise<DealerAddress>{if(!Number.isFinite(latitude)||!Number.isFinite(longitude)||Math.abs(latitude)>90||Math.abs(longitude)>180)throw new AddressServiceError("Invalid map coordinates.",400);const result=await request<{suggestions?:Array<{id?:unknown}>}>(`/nearest/${latitude}/${longitude}?top=1`,`reverse:${latitude.toFixed(5)}:${longitude.toFixed(5)}`);const id=clean(result.suggestions?.[0]?.id);if(!id)throw new AddressServiceError("No nearby address was found.",404);return getAddress(id)}
