import assert from "node:assert/strict";
import { randomUUID } from "node:crypto";
import { readFileSync } from "node:fs";
import { test } from "node:test";
import { PGlite } from "@electric-sql/pglite";
import { marketplaceFeeForPrice, validateMarketplaceFeeBands } from "@/lib/marketplace-fees";

const migration = readFileSync("supabase/migrations/20260930000100_marketplace_fee_bands_and_overrides.sql", "utf8");
const bands = [
  { min_purchase_price: 0, max_purchase_price: 2000, fee_amount: 49 },
  { min_purchase_price: 2000, max_purchase_price: 4000, fee_amount: 79 },
  { min_purchase_price: 4000, max_purchase_price: 6000, fee_amount: 99 },
  { min_purchase_price: 6000, max_purchase_price: 10000, fee_amount: 129 },
  { min_purchase_price: 10000, max_purchase_price: null, fee_amount: 149 },
];

test("marketplace fee boundaries and validation", () => {
  assert.equal(marketplaceFeeForPrice(1500, bands), 49);
  assert.equal(marketplaceFeeForPrice(2000, bands), 79);
  assert.equal(marketplaceFeeForPrice(3999, bands), 79);
  assert.equal(marketplaceFeeForPrice(4000, bands), 99);
  assert.equal(marketplaceFeeForPrice(6000, bands), 129);
  assert.equal(marketplaceFeeForPrice(10000, bands), 149);
  assert.equal(validateMarketplaceFeeBands(bands), null);
  assert.match(validateMarketplaceFeeBands([{ min_purchase_price: 0, max_purchase_price: 3000, fee_amount: 1 }, { min_purchase_price: 2000, max_purchase_price: null, fee_amount: 2 }]) ?? "", /continuous/);
});

test("isolated PostgreSQL: fee settings, snapshots, overrides and purchase are secure and idempotent", async () => {
  const db = new PGlite();
  const staff = randomUUID();
  const dealer = randomUUID();
  const dealerUser = randomUUID();
  try {
    await db.exec(`
      create role anon; create role authenticated; create role service_role bypassrls;
      create schema auth; create table auth.users(id uuid primary key);
      create table public.dealer_users(id uuid primary key,role text not null,active boolean not null default true);
      create function public.crm_staff_can_access() returns boolean language sql stable as $$ select false $$;
      create function public.crm_set_updated_at() returns trigger language plpgsql as $$ begin new.updated_at=now(); return new; end $$;
      create table public.dealer_portal_accounts(id uuid primary key,trading_name text,account_status text,attribution_period_days integer,successful_purchase_fee numeric);
      create table public.website_leads(id bigint generated by default as identity primary key,opportunity_mode text,marketplace_status text,marketplace_accepted_offer_id uuid,marketplace_accepted_at timestamptz,marketplace_fee_amount numeric,accepted_offer_amount numeric,accepted_offer_dealer_account_id uuid,status text,assigned_to text,updated_at timestamptz default now(),purchased_at timestamptz);
      create table public.dealer_lead_allocations(id uuid primary key default gen_random_uuid(),website_lead_id bigint,dealer_account_id uuid,allocation_status text,updated_at timestamptz default now());
      create table public.dealer_offers(id uuid primary key default gen_random_uuid(),website_lead_id bigint,dealer_account_id uuid,dealer_user_id uuid,allocation_id uuid,amount_pence integer,note text,status text,submitted_at timestamptz default now(),revised_at timestamptz,withdrawn_at timestamptz,accepted_at timestamptz,viewed_by_seller_at timestamptz,created_at timestamptz default now(),updated_at timestamptz default now());
      create table public.dealer_lead_claims(id uuid primary key default gen_random_uuid(),website_lead_id bigint,dealer_account_id uuid,dealer_user_id uuid,allocation_id uuid,status text,attribution_expires_at timestamptz,outcome_at timestamptz,updated_at timestamptz default now());
      create table public.dealer_purchases(id uuid primary key default gen_random_uuid(),website_lead_id bigint,claim_id uuid,dealer_account_id uuid,purchase_type text,purchase_price numeric,purchase_date date,collection_date date,mileage_at_purchase integer,notes text,reported_by uuid,reported_at timestamptz default now(),created_at timestamptz default now());
      create unique index dealer_purchases_claim_unique_idx on public.dealer_purchases(claim_id);
      create table public.dealer_purchase_fees(id uuid primary key default gen_random_uuid(),purchase_id uuid,dealer_account_id uuid,website_lead_id bigint,fee_amount numeric,status text,credit_amount numeric,adjustment_amount numeric,invoice_reference text,invoiced_amount numeric,paid_amount numeric,outstanding_amount numeric,invoiced_at timestamptz,invoiced_by uuid,paid_at timestamptz,paid_by uuid,credited_at timestamptz,voided_at timestamptz,voided_by uuid,notes text,created_at timestamptz default now(),updated_at timestamptz default now());
      create unique index dealer_purchase_fees_purchase_unique_idx on public.dealer_purchase_fees(purchase_id);
      create table public.dealer_lead_notes(id uuid primary key default gen_random_uuid(),website_lead_id bigint,claim_id uuid,dealer_account_id uuid,dealer_user_id uuid,note_type text,body text,created_at timestamptz default now());
      create table public.dealer_portal_audit_events(id bigint generated always as identity primary key,website_lead_id bigint,dealer_account_id uuid,dealer_user_id uuid,event_type text,event_data jsonb,created_at timestamptz default now());
      create table public.dealer_fee_ledger_entries(id bigint generated always as identity primary key,fee_id uuid,purchase_id uuid,website_lead_id bigint,dealer_account_id uuid,entry_type text,amount numeric,previous_status text,new_status text,previous_amounts jsonb,new_amounts jsonb,note text,created_by uuid,created_at timestamptz default now());
      create table public.marketplace_fee_settings(id boolean primary key,successful_purchase_fee numeric,fee_trigger text,updated_at timestamptz default now(),updated_by uuid);
      insert into public.marketplace_fee_settings values(true,0,'purchase_reported',now(),null);
      alter default privileges in schema public grant all on tables to anon,authenticated;
    `);
    await db.exec(migration);
    await db.exec("grant select on all tables in schema public to service_role");
    await db.query("insert into auth.users(id) values($1),($2)", [staff, dealerUser]);
    await db.query("insert into dealer_users(id,role,active) values($1,'team_member',true),($2,'dealer',true)", [staff, dealerUser]);
    await db.query("insert into dealer_portal_accounts(id,trading_name,account_status,attribution_period_days,successful_purchase_fee) values($1,'QA Dealer','active',60,50)", [dealer]);

    const fee = async (price: number) => (await db.query<{ value: number }>("select public.marketplace_fee_for_purchase_price($1) value", [price])).rows[0].value;
    assert.equal(Number(await fee(1500)), 49); assert.equal(Number(await fee(2000)), 79); assert.equal(Number(await fee(3999)), 79);
    assert.equal(Number(await fee(4000)), 99); assert.equal(Number(await fee(6000)), 129); assert.equal(Number(await fee(10000)), 149);

    for (const role of ["anon", "authenticated"]) {
      await db.exec(`set role ${role}`);
      await assert.rejects(db.query("select public.marketplace_fee_for_purchase_price(4500)"), /permission denied/);
      await assert.rejects(db.query("select public.staff_replace_marketplace_fee_bands('[]'::jsonb,$1)", [staff]), /permission denied/);
      await assert.rejects(db.query("insert into public.marketplace_fee_bands(min_purchase_price,max_purchase_price,fee_amount) values(0,null,1)"), /permission denied/);
      await db.exec("reset role");
    }

    const lead = (await db.query<{ id: number }>("insert into website_leads(opportunity_mode,marketplace_status,status) values('marketplace_offer','offer_received','reviewing') returning id")).rows[0].id;
    const allocation = randomUUID();
    await db.query("insert into dealer_lead_allocations(id,website_lead_id,dealer_account_id,allocation_status) values($1,$2,$3,'available')", [allocation, lead, dealer]);
    const offer = (await db.query<{ id: string }>("insert into dealer_offers(website_lead_id,dealer_account_id,dealer_user_id,allocation_id,amount_pence,status) values($1,$2,$3,$4,450000,'submitted') returning id", [lead, dealer, dealerUser, allocation])).rows[0].id;
    await db.exec("set role service_role");
    await db.query("select public.seller_accept_marketplace_offer($1,$2)", [lead, offer]);
    await db.exec("reset role");
    const accepted = (await db.query<Record<string, unknown>>("select * from website_leads where id=$1", [lead])).rows[0];
    assert.equal(Number(accepted.marketplace_fee_default_amount), 99);
    assert.equal(Number(accepted.marketplace_fee_amount), 99);
    assert.equal((await db.query<{ count: number }>("select count(*)::int count from dealer_purchase_fees")).rows[0].count, 0);

    await db.exec("set role service_role");
    await assert.rejects(db.query("select public.staff_replace_marketplace_fee_bands($1::jsonb,$2)", [JSON.stringify([{ min_purchase_price: 0, max_purchase_price: 5000, fee_amount: 10 }, { min_purchase_price: 4000, max_purchase_price: null, fee_amount: 20 }]), staff]), /continuous/);
    const futureBands = bands.map(band => ({ ...band, fee_amount: band.min_purchase_price === 4000 ? 88 : band.fee_amount }));
    await db.query("select public.staff_replace_marketplace_fee_bands($1::jsonb,$2)", [JSON.stringify(futureBands), staff]);
    assert.equal(Number((await db.query<{ marketplace_fee_amount: number }>("select marketplace_fee_amount from website_leads where id=$1", [lead])).rows[0].marketplace_fee_amount), 99);
    await db.query("select public.staff_override_marketplace_fee($1,75,'dealer agreement',$2)", [lead, staff]);
    await db.query("select public.staff_override_marketplace_fee($1,0,'launch promotion',$2)", [lead, staff]);
    assert.equal(Number((await db.query<{ marketplace_fee_amount: number }>("select marketplace_fee_amount from website_leads where id=$1", [lead])).rows[0].marketplace_fee_amount), 0);
    await db.query("select public.staff_override_marketplace_fee($1,75,'dealer agreement confirmed',$2)", [lead, staff]);
    await db.exec("reset role");
    assert.equal(Number((await db.query<{ marketplace_fee_amount: number }>("select marketplace_fee_amount from website_leads where id=$1", [lead])).rows[0].marketplace_fee_amount), 75);
    assert.equal((await db.query<{ count: number }>("select count(*)::int count from marketplace_fee_override_audit where website_lead_id=$1", [lead])).rows[0].count, 3);

    const claim = (await db.query<{ id: string }>("select id from dealer_lead_claims where website_lead_id=$1", [lead])).rows[0].id;
    const purchaseReady = (await db.query<Record<string, unknown>>("select c.status,l.opportunity_mode,l.accepted_offer_dealer_account_id from dealer_lead_claims c join website_leads l on l.id=c.website_lead_id where c.id=$1", [claim])).rows[0];
    assert.equal(purchaseReady.status, "agreed_to_purchase");
    assert.equal(purchaseReady.opportunity_mode, "marketplace_offer");
    assert.equal(purchaseReady.accepted_offer_dealer_account_id, dealer);
    await db.exec("set role service_role");
    const first = (await db.query<{ result: { duplicate: boolean } }>("select public.record_marketplace_purchase($1,$2,$3,4500,current_date,null,null,'QA',true) result", [claim,dealer,dealerUser])).rows[0].result;
    const repeated = (await db.query<{ result: { duplicate: boolean } }>("select public.record_marketplace_purchase($1,$2,$3,4500,current_date,null,null,'QA',true) result", [claim,dealer,dealerUser])).rows[0].result;
    await db.exec("reset role");
    assert.equal(first.duplicate,false); assert.equal(repeated.duplicate,true);
    assert.equal((await db.query<{ count: number }>("select count(*)::int count from dealer_purchases where claim_id=$1", [claim])).rows[0].count,1);
    assert.equal((await db.query<{ count: number; fee: number }>("select count(*)::int count,max(fee_amount) fee from dealer_purchase_fees where website_lead_id=$1", [lead])).rows[0].count,1);
    assert.equal(Number((await db.query<{ fee: number }>("select max(fee_amount) fee from dealer_purchase_fees where website_lead_id=$1", [lead])).rows[0].fee),75);
  } finally {
    await db.close();
  }
});

test("application keeps marketplace and direct purchase fee paths separate", () => {
  const route = readFileSync("app/api/dealer-portal/claims/[id]/purchase/route.ts", "utf8");
  assert.match(route, /if \(marketplacePurchase\)[\s\S]*record_marketplace_purchase/);
  assert.match(route, /fee_source: "dealer_account"/);
  assert.doesNotMatch(readFileSync("apps/motorleads/app/api/seller/offers/[id]/accept/route.ts", "utf8"), /dealer_purchase_fees|record_marketplace_purchase/);
});
