export const WEBSITE_LEAD_STATUSES = ["new", "reviewing", "contacted", "offer_made", "accepted", "declined", "purchased", "closed", "purchase_agreed", "purchase_cancelled", "referred_to_dealer"] as const;
export const WEBSITE_VALUATION_STATUSES = ["pending", "in_progress", "valued", "offer_ready", "needs_review", "complete"] as const;
export const WEBSITE_LEAD_SOURCES = ["bikebuyeruk", "sellyourmotorbike", "motorcyclebuyer"] as const;

export type WebsiteLeadStatus = typeof WEBSITE_LEAD_STATUSES[number];
export type WebsiteValuationStatus = typeof WEBSITE_VALUATION_STATUSES[number] | string;
export type WebsiteLeadSource = typeof WEBSITE_LEAD_SOURCES[number] | string;

export type WebsiteLead = {
  id: number;
  owner: string | null;
  reg: string | null;
  make: string | null;
  model: string | null;
  year: string | null;
  engine: string | null;
  colour: string | null;
  mileage: string | null;
  owners: string | null;
  spare_keys: string | null;
  bike_condition: string | null;
  damage: string | null;
  history: string | null;
  service: string | null;
  mot: string | null;
  extras: string | null;
  price: string | null;
  fname: string | null;
  lname: string | null;
  email: string | null;
  phone: string | null;
  postcode: string | null;
  normalised_postcode?: string | null;
  latitude?: number | null;
  longitude?: number | null;
  location_display_name?: string | null;
  location_town?: string | null;
  geocoding_status?: string | null;
  geocoding_provider?: string | null;
  location_checked_at?: string | null;
  location_lookup_error?: string | null;
  distance_from_yesmoto_miles?: number | null;
  driving_distance_miles?: number | null;
  estimated_drive_minutes?: number | null;
  image1: string | null;
  image2: string | null;
  image3: string | null;
  image4: string | null;
  image5: string | null;
  image6: string | null;
  image7: string | null;
  image8: string | null;
  image9: string | null;
  image10: string | null;
  website: WebsiteLeadSource | null;
  date: string | null;
  Images: string | null;
  valuation_status: WebsiteValuationStatus | null;
  retail_estimate: number | null;
  suggested_offer: number | null;
  estimated_margin: number | null;
  similar_bikes: string | null;
  auto_trader_search: string | null;
  valuation_notes: string | null;
  "Motorway output": string | null;
  retail_check_id?: string | null;
  stock_bike_id?: string | null;
  purchase_agreed_at?: string | null;
  latest_referral_id?: string | null;
  latest_referred_dealer_id?: string | null;
  latest_referred_dealer_name?: string | null;
  latest_referred_at?: string | null;
  referral_count?: number | null;
  valuation_started_at?: string | null;
  valuation_completed_at?: string | null;
  valuation_error?: string | null;
  images: string[] | null;
  status: WebsiteLeadStatus | string | null;
  assigned_to: string | null;
  contacted_at: string | null;
  offer_made_at: string | null;
  purchased_at: string | null;
  internal_notes: string | null;
  created_at: string | null;
  updated_at: string | null;
  resolved_images?: string[];
};

export type WebsiteLeadUpdate = Partial<Pick<WebsiteLead,
  "valuation_status" | "retail_estimate" | "suggested_offer" | "estimated_margin" | "similar_bikes" |
  "auto_trader_search" | "valuation_notes" | "Motorway output" | "internal_notes" | "status" |
  "assigned_to" | "contacted_at" | "offer_made_at" | "purchased_at"
>> & {
  retail_check_id?: string | null;
  valuation_started_at?: string | null;
  valuation_completed_at?: string | null;
  valuation_error?: string | null;
  normalised_postcode?: string | null;
  latitude?: number | null;
  longitude?: number | null;
  location_display_name?: string | null;
  location_town?: string | null;
  geocoding_status?: string | null;
  geocoding_provider?: string | null;
  location_checked_at?: string | null;
  location_lookup_error?: string | null;
  distance_from_yesmoto_miles?: number | null;
  driving_distance_miles?: number | null;
  estimated_drive_minutes?: number | null;
};
