import type { Metadata } from "next";
import Link from "next/link";

export const metadata:Metadata={title:"Used Motorcycle Warranty",description:"Qualifying YesMoto motorcycles include a 3-month Warranty First warranty and nationwide support."};
const included=["3-month Warranty First warranty","Parts and labour cover, subject to terms","Valid at any VAT-registered UK garage","Free roadside assistance, excluding home start"];
const process=[{title:"Contact Warranty First",copy:"Claims are handled directly by their specialist team."},{title:"Choose a local garage",copy:"Use a VAT-registered garage near you—there is normally no need to return to Brighton."},{title:"Assessment and support",copy:"Warranty First works with the garage under the terms of your cover."}];

export default function Warranty(){return <>
  <section className="info-hero warranty-hero"><div className="wide"><p>WARRANTY FIRST COVER</p><h1>RIDE AWAY<br/><em>WITH CONFIDENCE.</em></h1><h2>Nationwide support included with every qualifying retail motorcycle.</h2><div><Link href="/used-bikes">Browse motorcycles</Link><Link href="/contact" className="outline">Ask about warranty</Link></div></div></section>
  <section className="warranty-badge wide"><div><strong>3</strong><span>month warranty</span></div><p>Every qualifying motorcycle and scooter supplied by YesMoto includes Warranty First cover for added reassurance after purchase.</p></section>
  <section className="info-intro wide"><div><p className="about-kicker">WHAT’S INCLUDED?</p><h2>PEACE OF MIND, WHEREVER YOU RIDE.</h2></div><div className="warranty-included">{included.map(item=><span key={item}>{item}</span>)}</div></section>
  <section className="warranty-panels wide"><article><p className="about-kicker">MANUFACTURER’S WARRANTY</p><h2>CONTINUOUS COVER</h2><p>If your motorcycle still has manufacturer warranty remaining, it stays in place until expiry. Your three-month Warranty First cover then provides continued reassurance.</p></article><article><p className="about-kicker">EXTEND YOUR COVER</p><h2>UP TO 24 MONTHS</h2><p>Warranty First offers extended warranty options for up to 24 months. Ask our team about longer-term cover when purchasing your motorcycle.</p></article></section>
  <section className="claim-section"><div className="wide"><p className="about-kicker">MAKING A CLAIM</p><h2>STRAIGHTFORWARD NATIONWIDE SUPPORT.</h2><div>{process.map((step,index)=><article key={step.title}><span>{index+1}</span><h3>{step.title}</h3><p>{step.copy}</p></article>)}</div></div></section>
  <section className="warranty-contact wide"><div><p className="about-kicker">WARRANTY FIRST</p><h2>CLAIMS CONTACT</h2><p>Warranty claims are handled directly by Warranty First.</p></div><div><a href="tel:01733830278">01733 830278</a><a href="mailto:hello@warrantyfirst.co.uk">hello@warrantyfirst.co.uk</a><a href="https://www.warrantyfirst.co.uk" target="_blank" rel="noreferrer">warrantyfirst.co.uk ↗</a></div></section>
  <section className="why-warranty"><div className="wide"><p className="about-kicker">WHY WARRANTY FIRST?</p><h2>TRUSTED SUPPORT, CLOSE TO HOME.</h2><p>We carefully prepare every motorcycle, but unexpected mechanical faults can occasionally occur. Warranty First provides nationwide support and the flexibility to use a local VAT-registered garage rather than returning the motorcycle to Brighton.</p></div></section>
  <section className="info-cta"><div className="wide"><p>YOUR NEXT MOTORCYCLE</p><h2>PREPARED, PROTECTED, READY TO RIDE.</h2><div><Link href="/used-bikes">Browse motorcycles</Link><Link href="/contact" className="outline">Ask a warranty question</Link></div></div></section>
  </>}
