"use client";
import Link from "next/link";
import { useMemo, useState } from "react";
import { useRouter } from "next/navigation";
import { money } from "@/lib/mock-data";
import type { StockBike } from "@/lib/stock";

export type StockFilter="active"|"live"|"reserved"|"sold"|"prep"|"all";
const normal=(value:string)=>value.trim().toLowerCase().replace(/[_-]+/g," ").replace(/\s+/g," ");
const slugify=(value:string)=>value.toLowerCase().replace(/[^a-z0-9]+/g,"-").replace(/^-|-$/g,"");
const hasPublicAdvert=(bike:StockBike)=>["in stock","on forecourt","reserved"].includes(normal(bike.status))&&bike.price>0&&Boolean(bike.make)&&Boolean(bike.model);

export function AdminStockTable({bikes,initialFilter="active",initialQuery="",warning=""}:{bikes:StockBike[];initialFilter?:StockFilter;initialQuery?:string;warning?:string}){
  const router=useRouter(); const [query,setQuery]=useState(initialQuery); const [filter,setFilter]=useState<StockFilter>(initialFilter);
  const updateUrl=(nextFilter:StockFilter,nextQuery:string)=>{const params=new URLSearchParams();if(nextFilter!=="active")params.set("filter",nextFilter);if(nextQuery)params.set("q",nextQuery);router.replace(`/admin/stock${params.size?`?${params}`:""}`,{scroll:false})};
  const shown=useMemo(()=>bikes.filter(bike=>{const status=normal(bike.status);const statusMatch=filter==="all"||(filter==="active"&&["in stock","on forecourt","reserved","prep"].includes(status))||(filter==="live"&&["in stock","on forecourt"].includes(status))||(filter==="reserved"&&status==="reserved")||(filter==="sold"&&["sold","sale completed"].includes(status))||(filter==="prep"&&status==="prep");const searchMatch=!query||`${bike.make} ${bike.model} ${bike.registration}`.toLowerCase().includes(query.toLowerCase());const warningMatch=warning==="image"?(!bike.image||bike.image==="/bike-placeholder.svg"):warning==="price"?bike.price<=0:true;return statusMatch&&searchMatch&&warningMatch}),[bikes,filter,query,warning]);
  const openRow=(bike:StockBike)=>{if(hasPublicAdvert(bike))router.push(`/used-bikes/${slugify([bike.make,bike.model,bike.registration].filter(Boolean).join("-"))}`);else router.push(`/admin/stock?filter=all&q=${encodeURIComponent(bike.registration||`${bike.make} ${bike.model}`)}`)};

  return <><div className="admin-filters"><input value={query} onChange={event=>{setQuery(event.target.value);updateUrl(filter,event.target.value)}} placeholder="Search stock..."/><select value={filter} onChange={event=>{const value=event.target.value as StockFilter;setFilter(value);updateUrl(value,query)}}><option value="active">Active stock</option><option value="live">In Stock</option><option value="reserved">Reserved</option><option value="sold">Sold</option><option value="prep">Prep</option><option value="all">All stock</option></select><button type="button">{shown.length} results</button></div><div className="table-wrap"><table className="admin-table"><thead><tr><th>Bike</th><th>Registration</th><th>Year</th><th>Mileage</th><th>Sale price</th><th>Status</th><th>Ready</th><th>Purchase price</th><th>Profit</th><th>Actions</th></tr></thead><tbody>{shown.map(bike=>{const publicAdvert=hasPublicAdvert(bike);const slug=slugify([bike.make,bike.model,bike.registration].filter(Boolean).join("-"));return <tr className={publicAdvert?"clickable-row":""} onClick={()=>openRow(bike)} key={bike.id}><td><div className="stock-bike"><div className="stock-image-wrap"><img src={bike.image} alt=""/>{(!bike.image||bike.image==="/bike-placeholder.svg")&&<span title="Image missing">!</span>}</div><b>{bike.make||"Make missing"}<small>{bike.model||"Model missing"}</small></b></div></td><td>{bike.registration||"—"}</td><td>{bike.year||"—"}</td><td>{bike.mileage?`${bike.mileage.toLocaleString("en-GB")} miles`:"—"}</td><td>{bike.price>0?<b>{money(bike.price)}</b>:<span className="data-warning">Price missing</span>}</td><td><span className={`status ${normal(bike.status).replaceAll(' ','-')}`}>{bike.status||"Unknown"}</span>{bike.workshopStatus&&<small className="workshop-note">{bike.workshopStatus}</small>}</td><td><Toggle on={bike.readyForSale}/></td><td>{money(bike.purchasePrice)}</td><td>{money(bike.profit)}</td><td>{publicAdvert?<Link className="advert-link" href={`/used-bikes/${slug}`} onClick={event=>event.stopPropagation()}>Public advert ↗</Link>:<span className="muted-action">Not public</span>}</td></tr>})}</tbody></table></div></>;
}
export function Toggle({on}:{on:boolean}){return <button aria-label="Status toggle" className={`toggle ${on?'on':''}`} onClick={event=>event.stopPropagation()}><i/></button>}
