"use client";

import { useEffect, useMemo, useState } from "react";
import type { StockApiResponse, SupabaseStockBike } from "@/lib/stock-bike-types";

const money=(value:number|null)=>value==null?"Price unavailable":new Intl.NumberFormat("en-GB",{style:"currency",currency:"GBP",maximumFractionDigits:0}).format(value);
const normal=(value:string)=>value.trim().toLowerCase().replace(/[_-]+/g," ");

export function StockPageClient(){
  const [stock,setStock]=useState<SupabaseStockBike[]>([]);const [query,setQuery]=useState("");const [loading,setLoading]=useState(true);const [error,setError]=useState("");
  useEffect(()=>{const controller=new AbortController();async function load(){try{const response=await fetch("/api/stock",{signal:controller.signal});const data=await response.json() as StockApiResponse;if(!response.ok)throw new Error(data.error||"Unable to load stock.");setStock(data.stock);if(data.error)setError(data.error)}catch(caught){if(!controller.signal.aborted)setError(caught instanceof Error?caught.message:"Unable to load stock.")}finally{if(!controller.signal.aborted)setLoading(false)}}load();return()=>controller.abort()},[]);
  const counts=useMemo(()=>({total:stock.length,inStock:stock.filter(bike=>["in stock","on forecourt","available"].includes(normal(bike.status))).length,reserved:stock.filter(bike=>normal(bike.status)==="reserved").length,sold:stock.filter(bike=>["sold","sale completed"].includes(normal(bike.status))).length}),[stock]);
  const shown=useMemo(()=>stock.filter(bike=>!query||`${bike.registration??""} ${bike.make??""} ${bike.model??""} ${bike.variant??""} ${bike.status}`.toLowerCase().includes(query.toLowerCase())),[stock,query]);
  return <><section className="stock-page-hero"><div className="wide"><p>YESMOTO INVENTORY</p><h1>MOTORCYCLE STOCK</h1><span>Supabase stock management foundation</span></div></section><div className="stock-page wide"><div className="stock-counts"><article><span>Total stock</span><strong>{counts.total}</strong></article><article><span>In stock</span><strong>{counts.inStock}</strong></article><article><span>Reserved</span><strong>{counts.reserved}</strong></article><article><span>Sold</span><strong>{counts.sold}</strong></article></div><div className="stock-search"><input value={query} onChange={event=>setQuery(event.target.value)} placeholder="Search registration, make or model…"/><span>{shown.length} motorcycles</span></div>{loading?<div className="stock-state"><i/>Loading stock…</div>:error&&stock.length===0?<div className="stock-state error"><b>Stock unavailable</b><span>{error}</span></div>:shown.length===0?<div className="stock-state"><b>No motorcycles found</b><span>{query?"Try a different search.":"Stock will appear here after the first Supabase import."}</span></div>:<div className="supabase-stock-grid">{shown.map(bike=><article key={bike.id}><div className="supabase-stock-image">{bike.primary_image_url?<img src={bike.primary_image_url} alt={`${bike.make??""} ${bike.model??""}`}/>:<div><span>Y</span><small>Image coming soon</small></div>}<b className={`stock-status ${normal(bike.status).replaceAll(" ","-")}`}>{bike.status}</b></div><div className="supabase-stock-copy"><p>{bike.registration||"Registration pending"}</p><h2>{bike.year||""} {bike.make||"Unknown make"} {bike.model||"Unknown model"}</h2>{bike.variant&&<h3>{bike.variant}</h3>}<div><span>{bike.mileage==null?"Mileage unavailable":`${bike.mileage.toLocaleString("en-GB")} miles`}</span><strong>{money(bike.price)}</strong></div></div></article>)}</div>}</div></>;
}
