import type { Metadata } from "next";
import Link from "next/link";
import { getWebsitePageByPath, metadataFromWebsitePage } from "@/lib/website-pages";

export async function generateMetadata():Promise<Metadata>{return metadataFromWebsitePage(await getWebsitePageByPath("/reserve-online"),{title:"Reserve Your Motorcycle Online",description:"Reserve a YesMoto motorcycle online for £99 and secure it for up to seven days.",path:"/reserve-online"})}
const steps=[{number:"01",title:"Find your motorcycle",copy:"Choose the motorcycle or scooter that’s right for you from our current stock."},{number:"02",title:"Reserve online for £99",copy:"Select Reserve on the advert and complete the secure online reservation."},{number:"03",title:"We contact you",copy:"Our team will discuss finance, delivery, collection and any questions you have."},{number:"04",title:"Complete your purchase",copy:"Pay the remaining balance and arrange delivery or an appointment to collect."}];
const remoteDetails=["50–100 high-quality photographs","A detailed walkaround video","Comprehensive descriptions","Service history information where available"];
const nextSteps=["Motorcycle finance if required","Nationwide delivery","Collection by appointment","Payment of the remaining balance"];
const terms=["The £99 fee is deducted from the final purchase price.","Reservations are normally held for up to 7 days.","If we cannot contact you within 48 hours, the reservation may be cancelled and the motorcycle made available again.","If you decide not to proceed, the reservation fee may be retained.","If a motorcycle issue prevents the sale, your reservation fee will be refunded in full."];

export default function ReserveOnline(){return <>
  <section className="info-hero reserve-hero"><div className="wide"><p>RESERVE ONLINE · 24/7</p><h1>FOUND THE RIGHT<br/><em>MOTORCYCLE?</em></h1><h2>Secure it online for just £99.</h2><div><Link href="/used-bikes">Find a motorcycle</Link><Link href="/contact" className="outline">Ask a question</Link></div></div></section>
  <section className="info-proof wide"><article><strong>£99</strong><span>Reservation fee</span></article><article><strong>7 days</strong><span>Normally secured for</span></article><article><strong>24/7</strong><span>Online availability</span></article><article><strong>90%</strong><span>Customers buying remotely</span></article></section>
  <section className="info-intro wide"><div><p className="about-kicker">RESERVE WITH CONFIDENCE</p><h2>YOUR BIKE, HELD WHILE YOU FINALISE THE DETAILS.</h2></div><div><p>Reserving a motorcycle gives you time to complete your purchase without worrying that somebody else will buy it first. The process is quick, straightforward and available through our website at any time.</p><p>Your £99 reservation fee is deducted from the motorcycle’s final purchase price.</p></div></section>
  <section className="process-section"><div className="wide"><p className="about-kicker">HOW IT WORKS</p><h2>FROM ADVERT TO YOUR GARAGE</h2><div className="process-grid">{steps.map(step=><article key={step.number}><span>{step.number}</span><h3>{step.title}</h3><p>{step.copy}</p></article>)}</div></div></section>
  <section className="split-info wide"><article><p className="about-kicker">BUYING REMOTELY?</p><h2>EVERY DETAIL, BEFORE YOU DECIDE.</h2><p>Around 90% of our customers buy without visiting in person. Most YesMoto adverts give you everything needed to make an informed decision:</p><ul>{remoteDetails.map(item=><li key={item}>{item}</li>)}</ul><p>Need another photograph, video or detail? Just ask—we’re always happy to help.</p></article><article className="accent-card"><p className="about-kicker">WHAT HAPPENS NEXT?</p><h2>A REAL PERSON TAKES IT FROM HERE.</h2><p>Once your reservation arrives, a member of our team will contact you, answer your questions and help arrange:</p><ul>{nextSteps.map(item=><li key={item}>{item}</li>)}</ul><Link href="/contact">Speak to YesMoto →</Link></article></section>
  <section className="terms-section"><div className="wide"><div><p className="about-kicker">CLEAR FROM THE START</p><h2>RESERVATION TERMS</h2><p>We keep the process simple and transparent. Please read these points before placing a reservation.</p></div><div>{terms.map((term,index)=><p key={term}><span>{index+1}</span>{term}</p>)}</div></div></section>
  <section className="info-cta"><div className="wide"><p>READY WHEN YOU ARE</p><h2>CHOOSE YOUR NEXT MOTORCYCLE.</h2><div><Link href="/used-bikes">Browse motorcycles</Link><Link href="/contact" className="outline">Need more information?</Link></div></div></section>
  </>}
