"use client";
import {useEffect,useRef,useState} from "react";
export interface AddressValue {buildingNumber:string;buildingName:string;addressLine1:string;addressLine2:string;addressLine3:string;town:string;county:string;postcode:string;country:string;latitude:number|null;longitude:number|null;formattedAddress?:string[]}
export interface AddressLookupProps {value:AddressValue;onChange:(value:AddressValue)=>void;readonly?:boolean;required?:boolean}
type Suggestion={id:string;label:string};const searchCache=new Map<string,Suggestion[]>();
const field=(value:string)=>value??"";
export function AddressLookup({value,onChange,readonly=false,required=false}:AddressLookupProps){const [term,setTerm]=useState(""),[suggestions,setSuggestions]=useState<Suggestion[]>([]),[loading,setLoading]=useState(false),[error,setError]=useState(""),[manual,setManual]=useState(false);const request=useRef(0);
  useEffect(()=>{const query=term.trim();if(query.length<2){setSuggestions([]);setError("");return}const timer=setTimeout(async()=>{const token=++request.current;const cached=searchCache.get(query.toLowerCase());if(cached){setSuggestions(cached);return}setLoading(true);setError("");try{const response=await fetch(`/api/address/autocomplete?q=${encodeURIComponent(query)}`);const result=await response.json() as {suggestions?:Suggestion[];error?:string};if(token!==request.current)return;if(!response.ok)throw new Error(result.error||"Unable to search addresses.");const rows=result.suggestions??[];searchCache.set(query.toLowerCase(),rows);setSuggestions(rows);if(!rows.length)setError("No matching addresses. You can enter it manually.")}catch(caught){if(token===request.current)setError(caught instanceof Error?caught.message:"Address search unavailable.")}finally{if(token===request.current)setLoading(false)}},300);return()=>clearTimeout(timer)},[term]);
  async function select(suggestion:Suggestion){setLoading(true);setError("");try{const response=await fetch(`/api/address/get?id=${encodeURIComponent(suggestion.id)}`);const result=await response.json() as {address?:AddressValue;error?:string};if(!response.ok||!result.address)throw new Error(result.error||"Unable to retrieve address.");onChange(result.address);setTerm(suggestion.label);setSuggestions([])}catch(caught){setError(caught instanceof Error?caught.message:"Address lookup unavailable.");setManual(true)}finally{setLoading(false)}}
  const update=(key:keyof AddressValue,next:string)=>onChange({...value,[key]:key==="latitude"||key==="longitude"?(next===""?null:Number(next)):next});
  return <div className="shared-address-lookup"><label><span>Address search{required?" *":""}</span><input value={term} onChange={event=>setTerm(event.target.value)} placeholder="Type postcode, street or address…" autoComplete="off" readOnly={readonly} required={required&&!value.addressLine1} aria-expanded={suggestions.length>0}/>{loading&&<i>Searching…</i>}</label>{suggestions.length>0&&<div className="address-suggestions" role="listbox">{suggestions.map(item=><button type="button" role="option" onClick={()=>void select(item)} key={item.id}>{item.label}</button>)}</div>}{error&&<p>{error}</p>}{!readonly&&<button className="manual-address-toggle" type="button" onClick={()=>setManual(open=>!open)}>{manual?"Hide manual fields":"Enter address manually"}</button>}{(manual||Boolean(value.addressLine1))&&<div className="manual-address-fields"><label><span>Building number</span><input value={field(value.buildingNumber)} onChange={event=>update("buildingNumber",event.target.value)} readOnly={readonly}/></label><label><span>Building name</span><input value={field(value.buildingName)} onChange={event=>update("buildingName",event.target.value)} readOnly={readonly}/></label><label className="full"><span>Address line 1</span><input value={field(value.addressLine1)} onChange={event=>update("addressLine1",event.target.value)} readOnly={readonly} required={required}/></label><label className="full"><span>Address line 2</span><input value={field(value.addressLine2)} onChange={event=>update("addressLine2",event.target.value)} readOnly={readonly}/></label><label className="full"><span>Address line 3</span><input value={field(value.addressLine3)} onChange={event=>update("addressLine3",event.target.value)} readOnly={readonly}/></label><label><span>Town</span><input value={field(value.town)} onChange={event=>update("town",event.target.value)} readOnly={readonly}/></label><label><span>County</span><input value={field(value.county)} onChange={event=>update("county",event.target.value)} readOnly={readonly}/></label><label><span>Postcode</span><input value={field(value.postcode)} onChange={event=>update("postcode",event.target.value.toUpperCase())} readOnly={readonly} required={required}/></label><label><span>Country</span><input value={field(value.country)} onChange={event=>update("country",event.target.value)} readOnly={readonly}/></label></div>}</div>}
