import type { Metadata } from "next";
import Link from "next/link";

export const metadata:Metadata={title:"Nationwide Motorcycle Delivery",description:"Safe, insured motorcycle delivery from YesMoto in Brighton throughout mainland UK."};
const deliveryPrices=[{value:"Free",label:"Within 20 miles of Brighton"},{value:"From £189",label:"Mainland UK, including VAT"},{value:"Quoted",label:"Scotland, Ireland and international"}];
const confidence=["Typically 50–100 high-quality photographs","Walkaround video on almost every motorcycle","Detailed, honest descriptions","Service history where available","Keys, accessories and documentation detailed","Additional photos, video or FaceTime on request"];
const preparation=["Structured Pre-Delivery Inspection","Vehicle history check","Minimum six months MOT","Professional valet before handover"];
const handover=["Explain the basic controls","Answer initial questions","Allow time to inspect the motorcycle","Help with online road tax where required"];
const faqs=[{q:"Can I buy without visiting?",a:"Yes. Around 90% of our customers purchase remotely using our detailed photography, walkaround videos and descriptions."},{q:"How much does delivery cost?",a:"Delivery is free within 20 miles of Brighton. Mainland UK delivery starts from £189 including VAT. Scotland, Northern Ireland and the Republic of Ireland are quoted individually."},{q:"How long does delivery take?",a:"Standard delivery is usually completed within 5 to 7 working days, and is often quicker depending on your location."},{q:"Can I collect instead?",a:"Absolutely. You can collect from our Brighton premises by appointment, with the same personal handover process."},{q:"Do you deliver internationally?",a:"Yes. We can deliver to UK shipping agents or ports ready for export; customers arrange onward international shipping."}];

export default function NationwideDelivery(){return <>
  <section className="info-hero delivery-hero"><div className="wide"><p>FROM BRIGHTON · ACROSS THE UK</p><h1>NATIONWIDE<br/><em>MOTORCYCLE DELIVERY.</em></h1><h2>Safe, professional transport directly to your door.</h2><div><Link href="/used-bikes">Browse motorcycles</Link><Link href="/contact" className="outline">Get a delivery quote</Link></div></div></section>
  <section className="delivery-prices wide">{deliveryPrices.map(item=><article key={item.label}><strong>{item.value}</strong><span>{item.label}</span></article>)}</section>
  <section className="info-intro wide"><div><p className="about-kicker">BUY REMOTELY WITH CONFIDENCE</p><h2>YOUR NEXT MOTORCYCLE, DELIVERED.</h2></div><div><p>Around 90% of YesMoto customers buy without visiting us. Detailed photography, walkaround videos and honest descriptions allow riders across the UK to choose confidently before arranging safe delivery to their door.</p><p>Whether it’s your first motorcycle, an upgrade or a scooter for commuting, we make the process straightforward from first enquiry to handover.</p></div></section>
  <section className="transport-feature"><div className="wide"><div><p className="about-kicker">PROFESSIONAL TRANSPORT</p><h2>FULLY INSURED. TRACKED. MOTORCYCLE SPECIALISTS.</h2><p>We use specialist motorcycle delivery companies experienced in transporting bikes safely across the UK. Our primary partner, Move Motorcycles, provides a fully insured and tracked service.</p><p>Most deliveries arrive within 5 to 7 working days, often sooner depending on location and scheduling. You’ll receive updates throughout.</p></div><div className="delivery-route"><span>YESMOTO</span><i>→</i><b>YOUR DOOR</b><small>Tracked throughout the journey</small></div></div></section>
  <section className="split-info wide"><article><p className="about-kicker">EVERY DETAIL UP FRONT</p><h2>BUYING ONLINE WITH CONFIDENCE</h2><ul>{confidence.map(item=><li key={item}>{item}</li>)}</ul></article><article><p className="about-kicker">BEFORE IT LEAVES US</p><h2>PREPARED TO BE ENJOYED</h2><p>Every retail motorcycle is individually assessed and prepared. Work may include servicing, tyres, brakes, safety inspections and road testing.</p><ul>{preparation.map(item=><li key={item}>{item}</li>)}</ul></article></section>
  <section className="handover-section"><div className="wide"><div><p className="about-kicker">DELIVERY DAY</p><h2>MORE THAN A DROP-OFF.</h2><p>Your delivery includes a personal handover. Allow around 10–30 minutes; finance purchases require identification checks before release.</p></div><div>{handover.map((item,index)=><p key={item}><span>{String(index+1).padStart(2,"0")}</span>{item}</p>)}</div></div></section>
  <section className="after-delivery wide"><div><p className="about-kicker">AFTER DELIVERY</p><h2>WE’RE STILL HERE.</h2></div><div><p>We’ll complete the DVLA ownership transfer online. Confirmation normally arrives by email, with the replacement V5 usually following within around one week.</p><p>If you have questions after delivery, the YesMoto team is always happy to help.</p></div></section>
  <section className="faq-section"><div className="wide"><p className="about-kicker">FREQUENTLY ASKED QUESTIONS</p><h2>DELIVERY, EXPLAINED.</h2><div>{faqs.map((item,index)=><details open={index===0} key={item.q}><summary>{item.q}<span>+</span></summary><p>{item.a}</p></details>)}</div></div></section>
  <section className="info-cta"><div className="wide"><p>BUY ONLINE FROM YESMOTO</p><h2>SIMPLE. TRANSPARENT. DELIVERED.</h2><div><Link href="/used-bikes">Browse motorcycles</Link><Link href="/contact" className="outline">Discuss delivery</Link></div></div></section>
  </>}
