import "server-only";import {getSupabaseAdmin} from "@/lib/supabase/admin";
export type AdvertSectionKey='advert_overview'|'vehicle_details'|'fitted_extras'|'workshop_preparation'|'handover'|'warranty'|'finance'|'delivery'|'why_buy';
export interface AdvertTemplate{id:string;section_key:AdvertSectionKey;enabled_by_default:boolean;title:string;default_text:string;display_order:number;editable_per_bike:boolean}
export interface PlaceholderImage{id:string;image_url:string;enabled:boolean;display_order:number}
export const sectionFieldMap:Record<AdvertSectionKey,string>={advert_overview:"intro_description",vehicle_details:"key_details",fitted_extras:"fitted_extras",workshop_preparation:"preparation_work",handover:"included_before_delivery",warranty:"warranty",finance:"finance_options",delivery:"delivery",why_buy:"why_buy_from_yesmoto"};
const defaultRows:Record<AdvertSectionKey,{title:string;text:string;order:number}>={advert_overview:{title:"Advert Overview",order:10,text:""},vehicle_details:{title:"Vehicle Details",order:20,text:""},fitted_extras:{title:"Fitted Extras",order:30,text:""},workshop_preparation:{title:"Preparation & Service Work Completed",order:40,text:"Before delivery, this {{year}} {{make}} {{model}} will undergo a full pre-delivery inspection and safety check in our workshop.\n\n- Annual service completed before delivery where required\n- Pre-delivery inspection carried out\n- Supplied with {{mot_months}} months MOT where applicable\n- Supplied with a {{warranty_months}}-month warranty\n- Fully checked and prepared in our workshop\n- HPI checked\n- Professionally valeted"},handover:{title:"What's Included Before Delivery",order:50,text:"Before handover, this {{make}} {{model}} will be fully prepared and checked.\n\n- Full PDI and safety inspection\n- MOT documentation where applicable\n- Service history and available documentation\n- Warranty included\n- Professional valet before collection or delivery"},warranty:{title:"Warranty Included",order:60,text:"This {{year}} {{make}} {{model}} is supplied with a {{warranty_months}}-month warranty for added peace of mind.\n\nPlease ask the YesMoto team for full warranty terms and coverage."},finance:{title:"Finance Options Available",order:70,text:"Flexible finance options may be available on this {{year}} {{make}} {{model}}, subject to status.\n\n- Hire Purchase options available\n- Options for a range of credit profiles\n- Simple application process\n- Contact the YesMoto team for a personalised quotation"},delivery:{title:"Nationwide Delivery Available",order:80,text:"Nationwide delivery is available for this {{year}} {{make}} {{model}}.\n\nContact the YesMoto team on {{phone}} for a personalised delivery quote."},why_buy:{title:"Why Buy From YesMoto",order:90,text:"- Nationwide delivery available\n- Reserve online with a {{deposit_amount}} deposit\n- All bikes inspected and prepared before handover\n- Transparent vehicle history and documentation\n- Friendly support from the YesMoto team"}};
const defaults:AdvertTemplate[]=(Object.entries(defaultRows) as [AdvertSectionKey,{title:string;text:string;order:number}][]).map(([section_key,row])=>({id:section_key,section_key,title:row.title,enabled_by_default:true,default_text:row.text,display_order:row.order,editable_per_bike:true}));
export async function getAdvertTemplateSettings(){const db=getSupabaseAdmin();const [{data:templates,error},{data:images,error:imageError}]=await Promise.all([db.from("dealer_advert_templates").select("id,section_key,enabled_by_default,title,default_text,display_order,editable_per_bike").order("display_order"),db.from("dealer_placeholder_images").select("id,image_url,enabled,display_order").order("display_order")]);if(error||imageError){if([error?.code,imageError?.code].some(code=>["42P01","PGRST205"].includes(code??"")))return {templates:defaults,placeholderImages:[] as PlaceholderImage[],migrationReady:false};throw error||imageError}return {templates:(templates??defaults) as AdvertTemplate[],placeholderImages:(images??[]) as PlaceholderImage[],migrationReady:true}}
export function advertDefaults(templates:AdvertTemplate[]){return Object.fromEntries(templates.filter(t=>t.enabled_by_default).map(t=>[sectionFieldMap[t.section_key],t.default_text]))}
