import "server-only";import {PDFDocument,StandardFonts,rgb,type PDFFont,type PDFPage} from "pdf-lib";import type {AwaitedInvoiceDocument} from "@/lib/invoice-pdf-types";
const cash=(n:number)=>`GBP ${Number(n||0).toFixed(2)}`;const safe=(value:unknown)=>String(value??"").replace(/[^\x20-\x7E]/g," ");
export async function buildInvoicePdf(d:AwaitedInvoiceDocument){const pdf=await PDFDocument.create(),regular=await pdf.embedFont(StandardFonts.Helvetica),bold=await pdf.embedFont(StandardFonts.HelveticaBold);let page=pdf.addPage([595,842]),y=790;const green=rgb(0,.78,.12),dark=rgb(.04,.06,.07),grey=rgb(.38,.42,.44);const put=(value:unknown,x:number,size=10,font:PDFFont=regular,color=dark,target:PDFPage=page)=>target.drawText(safe(value),{x,y,size,font,color});
 page.drawRectangle({x:0,y:780,width:595,height:62,color:dark});put(d.settings.business_name.toUpperCase(),40,24,bold,green);page.drawText(safe(d.invoice.status==="draft"?`PROFORMA ${d.settings.invoice_title}`:d.settings.invoice_title).toUpperCase(),{x:385,y:808,size:9,font:bold,color:rgb(1,1,1)});page.drawText(d.invoice.invoice_number,{x:385,y:786,size:15,font:bold,color:rgb(1,1,1)});
 y=750;put(`Invoice date: ${new Date(d.invoice.issued_at).toLocaleDateString("en-GB")}`,40);page.drawText(`Due: ${d.invoice.due_at?new Date(d.invoice.due_at).toLocaleDateString("en-GB"):"On receipt"}`,{x:390,y,size:10,font:regular,color:dark});y-=35;put("INVOICE TO",40,9,bold,green);put("FROM",330,9,bold,green);y-=18;put(d.customerName||"Customer",40,12,bold);page.drawText(safe(d.dealership.tradingName),{x:330,y,size:10,font:bold,color:dark});
 for(let i=0;i<Math.max(d.address.length,5);i++){y-=15;if(d.address[i])put(d.address[i].slice(0,45),40,9,regular,grey);const from=[d.dealership.address,d.dealership.phone,d.dealership.email,d.settings.company_number&&`Company: ${d.settings.company_number}`,d.settings.vat_number&&`VAT: ${d.settings.vat_number}`][i];if(from)page.drawText(safe(from).slice(0,48),{x:330,y,size:9,font:regular,color:grey})}
 y-=28;page.drawRectangle({x:40,y:y-34,width:515,height:48,color:rgb(.94,.97,.94)});page.drawText("MOTORCYCLE",{x:52,y:y-5,size:8,font:bold,color:green});page.drawText(safe(d.bikeName).slice(0,65),{x:52,y:y-23,size:12,font:bold,color:dark});page.drawText(safe(d.bike.registration),{x:460,y:y-23,size:10,font:bold,color:dark});y-=65;
 const head=()=>{page.drawRectangle({x:40,y:y-20,width:515,height:26,color:dark});for(const [label,x] of [["Description",50],["Qty",365],["Unit",405],["Total",500]] as const)page.drawText(label,{x,y:y-12,size:9,font:bold,color:rgb(1,1,1)});y-=29};head();for(const item of d.items){if(y<190){page=pdf.addPage([595,842]);y=790;head()}put(item.description.slice(0,55),50,9);page.drawText(String(item.quantity),{x:370,y,size:9,font:regular,color:dark});put(cash(item.unit_price),405,9);put(cash(item.line_total),495,9,bold);y-=23}
 y-=15;for(const [label,value,strong] of [["Subtotal",cash(d.invoice.subtotal),false],["Paid",`- ${cash(d.invoice.paid)}`,false],["BALANCE DUE",cash(d.invoice.balance),true]] as const){page.drawText(label,{x:355,y,size:strong?12:10,font:strong?bold:regular,color:dark});put(value,480,strong?13:9,bold,strong?green:dark);y-=22}
 y-=12;put("PAYMENT INSTRUCTIONS",40,9,bold,green);y-=17;const bank=d.payment.configured?`${d.payment.accountName} | ${d.payment.sortCode} | ${d.payment.accountNumber} | Ref ${d.payment.reference}`:d.settings.payment_instructions||`Contact ${d.settings.business_name} on ${d.dealership.phone} for payment details.`;put(bank.slice(0,105),40,8,regular,grey);y-=14;put(d.settings.vat_wording.slice(0,105),40,8,regular,grey);page.drawText(safe(d.settings.invoice_footer).slice(0,75),{x:40,y:50,size:8,font:bold,color:dark});page.drawText(safe(`${d.dealership.domain} | ${d.dealership.phone} | ${d.dealership.email}`),{x:40,y:35,size:8,font:regular,color:grey});return pdf.save()}
