import "server-only";

import { PDFDocument, StandardFonts, rgb } from "pdf-lib";
import type { SupabaseStockBike } from "@/lib/stock-bike-types";
import { normalizeSupabaseStockBike } from "@/lib/supabase-stock";
import type { PdiFormPayload } from "@/lib/stock-pdi-types";

const safe = (value: unknown) => String(value ?? "").replace(/[^\x20-\x7E]/g, " ");

export async function buildPdiPdf(bikeInput: SupabaseStockBike, payload: PdiFormPayload) {
  const bike = normalizeSupabaseStockBike(bikeInput);
  const pdf = await PDFDocument.create();
  const regular = await pdf.embedFont(StandardFonts.Helvetica);
  const bold = await pdf.embedFont(StandardFonts.HelveticaBold);
  let page = pdf.addPage([595, 842]);
  let y = 800;
  const green = rgb(0, 0.78, 0.12);
  const dark = rgb(0.04, 0.06, 0.07);
  const grey = rgb(0.38, 0.42, 0.44);

  function text(value: unknown, x: number, size = 10, font = regular, color = dark) {
    page.drawText(safe(value).slice(0, 90), { x, y, size, font, color });
  }

  function newPage() {
    page = pdf.addPage([595, 842]);
    y = 800;
  }

  page.drawRectangle({ x: 0, y: 774, width: 595, height: 68, color: dark });
  text("YESMOTO DIGITAL PDI", 40, 23, bold, green);
  page.drawText(new Date().toLocaleDateString("en-GB"), { x: 455, y: 804, size: 10, font: bold, color: rgb(1, 1, 1) });
  y = 742;
  text([bike.year, bike.make, bike.model, bike.variant].filter(Boolean).join(" "), 40, 17, bold);
  y -= 24;
  text(`Registration: ${bike.registration || "—"}   VIN: ${bike.vin || "—"}   Mileage: ${bike.mileage ? bike.mileage.toLocaleString("en-GB") : "—"}`, 40, 9, regular, grey);
  y -= 30;
  text(`Technician: ${payload.technicianName || "—"}`, 40, 11, bold);
  y -= 24;

  let currentSection = "";
  for (const item of payload.checklist) {
    if (y < 95) newPage();
    if (item.section !== currentSection) {
      currentSection = item.section;
      page.drawRectangle({ x: 40, y: y - 5, width: 515, height: 22, color: rgb(0.92, 0.96, 0.93) });
      text(currentSection.toUpperCase(), 50, 9, bold, green);
      y -= 28;
    }
    const result = item.result.toUpperCase();
    page.drawText(item.checked ? "✓" : "□", { x: 48, y, size: 11, font: bold, color: item.checked ? green : grey });
    page.drawText(safe(item.label).slice(0, 45), { x: 68, y, size: 9, font: regular, color: dark });
    page.drawText(result, { x: 365, y, size: 9, font: bold, color: item.result === "fail" ? rgb(0.75, 0.05, 0.1) : green });
    if (item.notes) page.drawText(safe(item.notes).slice(0, 35), { x: 420, y, size: 8, font: regular, color: grey });
    y -= 18;
  }

  y -= 18;
  if (y < 130) newPage();
  text("TECHNICIAN SIGNATURE", 40, 9, bold, green);
  y -= 18;
  page.drawRectangle({ x: 40, y: y - 48, width: 250, height: 60, borderColor: grey, borderWidth: 1 });
  if (payload.signatureDataUrl?.startsWith("data:image/png;base64,")) {
    try {
      const image = await pdf.embedPng(Buffer.from(payload.signatureDataUrl.split(",")[1], "base64"));
      page.drawImage(image, { x: 50, y: y - 40, width: 220, height: 42 });
    } catch {
      page.drawText("Signature image unavailable", { x: 52, y: y - 18, size: 8, font: regular, color: grey });
    }
  }
  page.drawText("Completed PDI form generated by DealerOS.", { x: 40, y: 40, size: 8, font: regular, color: grey });
  return pdf.save();
}
