/* eslint-disable @typescript-eslint/no-explicit-any -- Dynamic module/query adapter around the real handlers and PostgreSQL results. */
import { PGlite } from '@electric-sql/pglite';
import { readFileSync } from 'node:fs';
export async function sellerDatabase() {
 const db=new PGlite();
 const setup=readFileSync('supabase/migrations/20260910000100_motorgeeks_marketplace_offers.sql','utf8');
 const migration=readFileSync('supabase/migrations/20260921000400_seller_journey_reliability.sql','utf8');
 // Minimal surrounding app schema; seller tables and new functions are actual migration SQL.
 const fields=migration.match(/insert into public.website_leads\(([^)]+)\)/)![1].replace(/\s/g,'').split(',').filter(k=>k!=='seller_draft_id');
 const jsonFields=['seller_vehicle_snapshot','seller_condition','seller_profile','seller_progress','autotrader_vehicle_lookup_data','autotrader_vehicle_check_data'];
 await db.exec(`create role anon; create role authenticated; create role service_role bypassrls;
 create table public.website_leads(id bigint generated by default as identity primary key,${fields.map(k=>`${k} ${jsonFields.includes(k)?'jsonb':k==='consent_terms'?'boolean':k.endsWith('_at')?'timestamptz':'text'}`).join(',')},archived_at timestamptz,marketplace_accepted_offer_id uuid);
 create table public.dealer_portal_audit_events(id uuid default gen_random_uuid(),website_lead_id bigint,event_type text,event_data jsonb);
 create schema storage; create table storage.buckets(id text primary key,public boolean,file_size_limit bigint,allowed_mime_types text[]);
 insert into storage.buckets values('motorgeeks-seller-photos',false,15728640,array['image/jpeg']);`);
 for(const name of ['seller_valuation_drafts','lead_photos','seller_access_tokens']) {
  const start=setup.indexOf(`create table if not exists public.${name} (`);
  await db.exec(setup.slice(start,setup.indexOf('\n);',start)+3));
 }
 await db.exec(migration);
 await db.exec('alter table website_leads add column marketplace_fee_amount numeric; create table dealer_portal_accounts(id uuid primary key,successful_purchase_fee numeric); create table marketplace_fee_settings(id boolean,successful_purchase_fee numeric); create table dealer_lead_claims(id uuid); create table public.dealer_offers(id uuid primary key,website_lead_id bigint,status text,amount_pence int,note text,submitted_at timestamptz,revised_at timestamptz);');
 // Install actual existing RPC bodies too: revoked execution must fail before body evaluation.
 for(const name of ['dealer_submit_marketplace_offer','seller_accept_marketplace_offer','marketplace_purchase_fee_amount']){
  const start=setup.indexOf(`create or replace function public.${name}(`), body=setup.indexOf('$$',start),end=setup.indexOf('$$;',body+2);
  // These composite types are referenced when PostgreSQL compiles a PL/pgSQL body at first execution.
  await db.exec(setup.slice(start,end+3));
 }
 await db.exec(readFileSync('supabase/migrations/20260921000100_fix_marketplace_offer_conflict_retry.sql','utf8'));
 await db.exec(readFileSync('supabase/migrations/20260921000300_marketplace_rpc_server_only.sql','utf8'));
 await db.exec('grant usage on schema public to service_role,anon,authenticated; grant all on all tables in schema public to service_role; grant all on all sequences in schema public to service_role;');
 return db;
}
export async function rpc(db:PGlite,name:string,args:Record<string,unknown>) {
 const keys=Object.keys(args);
 return (await db.query<{result:any}>(`select public.${name}(${keys.map((k,i)=>`${k} => $${i+1}`).join(',')}) as result`,keys.map(k=>typeof args[k]==='object'?JSON.stringify(args[k]):args[k]))).rows[0].result;
}
