"use client";

import Link from "next/link";
import { useEffect, useMemo, useState } from "react";

type Row = {
  id:string;stockNumber:string|null;registration:string|null;make:string|null;model:string|null;year:number|null;status:string;purchaseDate:string|null;purchasePrice:number;preparationCosts:number;partsCost:number;labourCost:number;transportCosts:number;totalInvestment:number;advertisedPrice:number;targetRetail:number;currentRetailPrice:number;margin:number;profitPercent:number|null;daysInStock:number|null;ageDays:number|null;currentDepartment:string;assignedStaff:string|null;websiteLive:boolean;dealer5Synced:boolean;expectedGrossProfit:number;expectedNetProfit:number;actualNetProfit:number;soldDate:string|null;expectedArrivalDate:string|null;alerts:string[];
};
type Data = {rows:Row[];kpis:Record<string,number>;reports:Record<string,unknown>;charts:Record<string,{label:string;value:number}[]>};
type SortKey = keyof Row;

const money = (value:number)=>new Intl.NumberFormat("en-GB",{style:"currency",currency:"GBP",maximumFractionDigits:0}).format(value||0);
const number = (value:number)=>new Intl.NumberFormat("en-GB",{maximumFractionDigits:1}).format(value||0);
const labels:Record<string,string>={currentStockCost:"Current Stock Cost",purchasePendingCost:"Purchase Pending Cost",totalCapitalCommitted:"Total Capital Committed",expectedRetailValue:"Expected Retail Value",expectedGrossProfit:"Expected Gross Profit",expectedNetProfit:"Expected Net Profit",bikesInStock:"Bikes In Stock",purchasePendingCount:"Purchase Pending Count",averageDaysInStock:"Average Days In Stock",averageProfitPerBike:"Average Profit Per Bike",bikesOver30Days:"Bikes Over 30 Days",bikesOver60Days:"Bikes Over 60 Days",bikesOver90Days:"Bikes Over 90 Days",soldThisMonth:"Sold This Month",profitThisMonth:"Profit This Month",profitThisYear:"Profit This Year"};
const moneyKpis=new Set(["currentStockCost","purchasePendingCost","totalCapitalCommitted","expectedRetailValue","expectedGrossProfit","expectedNetProfit","averageProfitPerBike","profitThisMonth","profitThisYear"]);

export default function StockLedgerPage(){
  const [data,setData]=useState<Data|null>(null),[error,setError]=useState(""),[query,setQuery]=useState(""),[status,setStatus]=useState(""),[make,setMake]=useState(""),[model,setModel]=useState(""),[profit,setProfit]=useState(""),[days,setDays]=useState(""),[staff,setStaff]=useState(""),[sort,setSort]=useState<SortKey>("status"),[direction,setDirection]=useState<"asc"|"desc">("asc");
  useEffect(()=>{let active=true;fetch("/api/stock-ledger").then(async r=>{const p=await r.json();if(!r.ok)throw new Error(p.error||"Unable to load stock ledger.");if(active)setData(p)}).catch(e=>active&&setError(e instanceof Error?e.message:"Unable to load stock ledger."));return()=>{active=false}},[]);
  const rows=useMemo(()=>{const base=data?.rows??[],search=query.trim().toLowerCase();return base.filter(row=>{
    const text=[row.stockNumber,row.registration,row.make,row.model,row.year,row.status,row.assignedStaff].join(" ").toLowerCase();
    return (!search||text.includes(search))&&(!status||row.status===status)&&(!make||row.make===make)&&(!model||row.model===model)&&(!staff||row.assignedStaff===staff)&&(!profit||(profit==="negative"?row.margin<0:profit==="low"?row.margin>=0&&row.margin<500:row.margin>=1000))&&(!days||(days==="30"?(row.ageDays??0)>30:days==="60"?(row.ageDays??0)>60:days==="90"?(row.ageDays??0)>90:(row.ageDays??0)>180));
  }).sort((a,b)=>compare(a[sort],b[sort])*(direction==="asc"?1:-1))},[data,query,status,make,model,staff,profit,days,sort,direction]);
  const options=(key:keyof Row)=>Array.from(new Set((data?.rows??[]).map(row=>row[key]).filter(Boolean))).sort() as string[];
  function sortBy(key:SortKey){if(sort===key)setDirection(d=>d==="asc"?"desc":"asc");else{setSort(key);setDirection("asc")}}
  if(error)return <main className="admin-page stock-ledger-page"><div className="website-state error">{error}</div></main>;
  if(!data)return <main className="admin-page stock-ledger-page"><div className="website-state">Loading stock ledger...</div></main>;
  return <main className="admin-page stock-ledger-page">
    <div className="admin-heading"><div><h1>Stock Ledger</h1><p>Capital, stock ageing, expected profit and realised performance.</p></div><div className="stock-ledger-exports"><button onClick={()=>{window.location.href="/api/stock-ledger?export=current"}}>Current Stock CSV</button><button onClick={()=>{window.location.href="/api/stock-ledger?export=pending"}}>Purchase Pending CSV</button><button onClick={()=>{window.location.href="/api/stock-ledger?export=sold"}}>Sold Bikes CSV</button><button onClick={()=>{window.location.href="/api/stock-ledger?export=profit"}}>Profit Report CSV</button></div></div>
    <section className="ledger-kpis">{Object.entries(labels).map(([key,label])=><article className={String(key).includes("Profit")?"profit":""} key={key}><span>{label}</span><strong>{moneyKpis.has(key)?money(data.kpis[key]??0):number(data.kpis[key]??0)}</strong></article>)}</section>
    <section className="ledger-reports"><Report title="Monthly purchases" value={String(data.reports.monthlyPurchases??0)}/><Report title="Monthly sales" value={String(data.reports.monthlySales??0)}/><Report title="Monthly profit" value={money(Number(data.reports.monthlyProfit??0))}/><Report title="Average days to sell" value={number(Number(data.reports.averageDaysToSell??0))}/><Report title="Fastest selling bike" value={bikeName(data.reports.fastestSellingBike)}/><Report title="Highest profit bike" value={bikeName(data.reports.highestProfitBike)}/><Report title="Lowest profit bike" value={bikeName(data.reports.lowestProfitBike)}/><Report title="Most profitable make" value={groupName(data.reports.mostProfitableMake)}/><Report title="Most profitable model" value={groupName(data.reports.mostProfitableModel)}/></section>
    <section className="ledger-charts"><Chart title="Capital invested over time" data={data.charts.capitalOverTime}/><Chart title="Monthly profit" data={data.charts.monthlyProfit}/><Chart title="Monthly purchases" data={data.charts.monthlyPurchases}/><Chart title="Monthly sales" data={data.charts.monthlySales}/><Chart title="Stock ageing" data={data.charts.stockAgeing}/><Chart title="Profit by make" data={data.charts.profitByMake}/><Chart title="Profit by model" data={data.charts.profitByModel}/></section>
    <section className="ledger-filters"><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Search stock, reg, make, model, staff"/><select value={status} onChange={e=>setStatus(e.target.value)}><option value="">All statuses</option>{options("status").map(x=><option key={x}>{x}</option>)}</select><select value={make} onChange={e=>setMake(e.target.value)}><option value="">All makes</option>{options("make").map(x=><option key={x}>{x}</option>)}</select><select value={model} onChange={e=>setModel(e.target.value)}><option value="">All models</option>{options("model").map(x=><option key={x}>{x}</option>)}</select><select value={profit} onChange={e=>setProfit(e.target.value)}><option value="">Any profit</option><option value="negative">Negative margin</option><option value="low">Below £500</option><option value="strong">£1,000+</option></select><select value={days} onChange={e=>setDays(e.target.value)}><option value="">Any age</option><option value="30">Over 30 days</option><option value="60">Over 60 days</option><option value="90">Over 90 days</option><option value="180">Over 180 days</option></select><select value={staff} onChange={e=>setStaff(e.target.value)}><option value="">All assigned</option>{options("assignedStaff").map(x=><option key={x}>{x}</option>)}</select></section>
    <div className="ledger-table-wrap"><table className="ledger-table"><thead><tr>{(["stockNumber","registration","make","model","year","status","purchaseDate","purchasePrice","preparationCosts","partsCost","labourCost","transportCosts","totalInvestment","advertisedPrice","targetRetail","currentRetailPrice","margin","profitPercent","daysInStock","currentDepartment","assignedStaff","websiteLive","dealer5Synced"] as SortKey[]).map(key=><th key={key}><button onClick={()=>sortBy(key)}>{heading(key)}</button></th>)}<th>Alerts</th></tr></thead><tbody>{rows.map(row=><tr className={row.alerts.length?"warn":""} key={row.id}><td><Link href={`/admin/stock-ledger/${row.id}`}>{row.stockNumber||row.id}</Link></td><td>{row.registration||"-"}</td><td>{row.make||"-"}</td><td>{row.model||"-"}</td><td>{row.year||"-"}</td><td>{row.status}</td><td>{row.purchaseDate||"-"}</td><td>{money(row.purchasePrice)}</td><td>{money(row.preparationCosts)}</td><td>{money(row.partsCost)}</td><td>{money(row.labourCost)}</td><td>{money(row.transportCosts)}</td><td>{money(row.totalInvestment)}</td><td>{money(row.advertisedPrice)}</td><td>{money(row.targetRetail)}</td><td>{money(row.currentRetailPrice)}</td><td className={row.margin<0?"negative":"positive"}>{money(row.margin)}</td><td>{row.profitPercent==null?"-":`${number(row.profitPercent)}%`}</td><td>{row.daysInStock??"-"}</td><td>{row.currentDepartment}</td><td>{row.assignedStaff||"-"}</td><td>{row.websiteLive?"Yes":"No"}</td><td>{row.dealer5Synced?"Yes":"No"}</td><td>{row.alerts.map(a=><b key={a}>{a}</b>)}</td></tr>)}</tbody></table></div>
  </main>
}

function compare(a:unknown,b:unknown){if(typeof a==="number"||typeof b==="number")return Number(a??-Infinity)-Number(b??-Infinity);return String(a??"").localeCompare(String(b??""))}
function heading(key:string){return key.replace(/([A-Z])/g," $1").replace(/^./,c=>c.toUpperCase())}
function Report({title,value}:{title:string;value:string}){return <article><span>{title}</span><b>{value||"-"}</b></article>}
function bikeName(value:unknown){const row=value as Row|null;return row?[row.stockNumber,row.make,row.model].filter(Boolean).join(" "):"-"}
function groupName(value:unknown){const row=value as {label?:string;value?:number}|null;return row?.label?`${row.label} (${money(row.value??0)})`:"-"}
function Chart({title,data=[]}:{title:string;data?:{label:string;value:number}[]}){const max=Math.max(...data.map(d=>Math.abs(d.value)),1);return <article className="ledger-chart"><h2>{title}</h2><div>{data.map(d=><span key={d.label} title={`${d.label}: ${d.value}`}><i style={{height:`${Math.max(6,Math.abs(d.value)/max*100)}%`}} className={d.value<0?"negative":""}/><small>{d.label}</small></span>)}</div></article>}
