"use client";
import { useEffect, useMemo, useRef, useState } from "react";
const imageKey=(value:string)=>{try{const url=new URL(value);return `${url.origin}${url.pathname}`.toLowerCase()}catch{return value.split("?")[0].toLowerCase()}};
export function BikeGallery({images,alt}:{images:string[];alt:string}){
  const safe=useMemo(()=>{const seen=new Set<string>();const unique=images.filter(image=>{const key=imageKey(image);if(!key||seen.has(key))return false;seen.add(key);return true});return unique.length?unique:["/bike-placeholder.svg"]},[images]);const [index,setIndex]=useState(0),[open,setOpen]=useState(false),[reservationOpen,setReservationOpen]=useState(false);const touchStart=useRef<number|null>(null);const multiple=safe.length>1;
  const previous=()=>setIndex(current=>(current-1+safe.length)%safe.length),next=()=>setIndex(current=>(current+1)%safe.length);
  useEffect(()=>{const close=()=>{setOpen(false);setReservationOpen(true)};window.addEventListener("yesmoto:reservation-open",close);const observer=new MutationObserver(()=>setReservationOpen(document.body.classList.contains("reservation-open")));observer.observe(document.body,{attributes:true,attributeFilter:["class"]});return()=>{window.removeEventListener("yesmoto:reservation-open",close);observer.disconnect()}},[]);
  useEffect(()=>{if(!open)return;const onKey=(event:KeyboardEvent)=>{if(event.key==="Escape")setOpen(false);if(event.key==="ArrowLeft")previous();if(event.key==="ArrowRight")next()};document.addEventListener("keydown",onKey);const prior=document.body.style.overflow;document.body.style.overflow="hidden";return()=>{document.removeEventListener("keydown",onKey);document.body.style.overflow=prior}},[open,safe.length]);
  const endSwipe=(x:number)=>{if(touchStart.current===null)return;const distance=x-touchStart.current;if(Math.abs(distance)>45)(distance<0?next:previous)();touchStart.current=null};const swipe={onTouchStart:(event:React.TouchEvent)=>{if(!reservationOpen)touchStart.current=event.changedTouches[0].clientX},onTouchEnd:(event:React.TouchEvent)=>endSwipe(event.changedTouches[0].clientX)};
  const recover=()=>setIndex(current=>Math.min(current+1,safe.length-1));
  return <div className={`bike-gallery premium-gallery ${reservationOpen?"reservation-active":""}`} aria-hidden={reservationOpen||undefined}><div className="gallery-main" {...swipe}><button className="gallery-image-button" onClick={()=>!reservationOpen&&setOpen(true)} disabled={reservationOpen} aria-label="Open fullscreen photo gallery"><img src={safe[index]} alt={`${alt} photo ${index+1}`} onError={recover}/></button>{multiple&&!reservationOpen&&<><button className="gallery-arrow previous" onClick={previous} aria-label="Previous photo">‹</button><button className="gallery-arrow next" onClick={next} aria-label="Next photo">›</button></>} {!reservationOpen&&<><span className="gallery-counter">{index+1} / {safe.length}</span><button className="view-all-photos" onClick={()=>setOpen(true)}>View all {safe.length} photos</button></>}</div>{multiple&&<div className="gallery-thumbs" aria-label="Photo thumbnails">{safe.map((image,i)=><button className={i===index?"active":""} onClick={()=>setIndex(i)} disabled={reservationOpen} aria-label={`Show photo ${i+1}`} aria-current={i===index} key={`${imageKey(image)}-${i}`}><img src={image} alt="" onError={event=>{event.currentTarget.style.display="none"}}/><span>{i+1}</span></button>)}</div>}{open&&!reservationOpen&&<div className="gallery-lightbox" role="dialog" aria-modal="true" aria-label={`${alt} photo gallery`} {...swipe} onMouseDown={()=>setOpen(false)}><button className="lightbox-close" onClick={()=>setOpen(false)} aria-label="Close photo gallery">×</button><span className="lightbox-counter">{index+1} / {safe.length}</span>{multiple&&<button className="lightbox-arrow previous" onMouseDown={event=>event.stopPropagation()} onClick={previous}>‹</button>}<img src={safe[index]} alt={`${alt} photo ${index+1}`} onMouseDown={event=>event.stopPropagation()} onError={recover}/>{multiple&&<button className="lightbox-arrow next" onMouseDown={event=>event.stopPropagation()} onClick={next}>›</button>}</div>}</div>;
}
