"use client";
import { FormEvent, useEffect, useState } from "react";

export function ReserveButton({ bikeId, slug, bike, className = "", label = "Reserve online for £99" }: { bikeId: string; slug: string; bike: string; className?: string; label?: string }) {
  const [open, setOpen] = useState(false), [busy, setBusy] = useState(false), [error, setError] = useState("");
  useEffect(() => { if (!open) return; const close = (event: KeyboardEvent) => { if (event.key === "Escape") setOpen(false); }; document.addEventListener("keydown", close); document.body.style.overflow = "hidden"; return () => { document.removeEventListener("keydown", close); document.body.style.overflow = ""; }; }, [open]);
  async function submit(event: FormEvent<HTMLFormElement>) { event.preventDefault(); setBusy(true); setError(""); const form = new FormData(event.currentTarget); const response = await fetch("/api/stripe/create-checkout-session", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ ...Object.fromEntries(form), stock_bike_id: bikeId, slug, consent: form.get("consent") === "on" }) }); const result = await response.json() as { url?: string; error?: string }; if (!response.ok || !result.url) { setBusy(false); setError(result.error || "Unable to start secure checkout."); return; } window.location.assign(result.url); }
  return <><button type="button" className={className} onClick={() => setOpen(true)}>{label}</button>{open && <div className="reservation-modal" role="dialog" aria-modal="true" aria-label={`Reserve ${bike}`} onMouseDown={event => { if (event.target === event.currentTarget && !busy) setOpen(false); }}><form onSubmit={submit}><header><div><span>SECURE ONLINE RESERVATION</span><h2>Reserve {bike}</h2><p>Pay £99 securely through Stripe. We’ll hold the motorcycle for up to seven days and contact you to complete the purchase.</p></div><button type="button" aria-label="Close" onClick={() => setOpen(false)} disabled={busy}>×</button></header><div className="reservation-form-grid"><label><span>First name</span><input name="first_name" autoComplete="given-name" required /></label><label><span>Last name</span><input name="last_name" autoComplete="family-name" required /></label><label><span>Email</span><input name="email" type="email" autoComplete="email" required /></label><label><span>Phone</span><input name="phone" type="tel" autoComplete="tel" required /></label><label className="full reservation-consent"><input name="consent" type="checkbox" required /><span>I agree to the <a href="/reserve-online" target="_blank">reservation terms</a>. The £99 fee is deducted from the final purchase price.</span></label>{error && <p className="full auth-message">{error}</p>}<button className="full" disabled={busy}>{busy ? "Opening secure checkout…" : "Continue to secure £99 payment"}</button><small className="full">Payment details are entered securely on Stripe. YesMoto does not receive or store your card number.</small></div></form></div>}</>;
}
