"use client";
import { FormEvent, useEffect, useId, useState } from "react";
import { createPortal } from "react-dom";

const cleanPhone=(value:string)=>value.trim().replace(/\s+/g," ");
export function ReserveButton({ bikeId, slug, bike, className = "", label = "Reserve online for £99" }: { bikeId: string; slug: string; bike: string; className?: string; label?: string }) {
  const owner=useId();const [mounted,setMounted]=useState(false),[open,setOpen]=useState(false),[opening,setOpening]=useState(false),[busy,setBusy]=useState(false),[error,setError]=useState("");
  const [firstName,setFirstName]=useState(""),[lastName,setLastName]=useState(""),[email,setEmail]=useState(""),[phone,setPhone]=useState(""),[acceptedTerms,setAcceptedTerms]=useState(false);
  useEffect(()=>setMounted(true),[]);
  useEffect(()=>{const other=(event:Event)=>{if((event as CustomEvent<string>).detail!==owner)setOpen(false)};window.addEventListener("yesmoto:reservation-open",other);return()=>window.removeEventListener("yesmoto:reservation-open",other)},[owner]);
  useEffect(()=>{if(!open)return;document.body.classList.add("reservation-open");const close=(event:KeyboardEvent)=>{if(event.key==="Escape"&&!busy)setOpen(false)};document.addEventListener("keydown",close);return()=>{document.removeEventListener("keydown",close);document.body.classList.remove("reservation-open")}},[open,busy]);
  function openModal(){setOpening(true);setError("");window.dispatchEvent(new CustomEvent("yesmoto:reservation-open",{detail:owner}));requestAnimationFrame(()=>{setOpen(true);setOpening(false)})}
  function closeModal(){if(!busy)setOpen(false)}
  async function submit(event:FormEvent<HTMLFormElement>){event.preventDefault();const values={firstName:firstName.trim(),lastName:lastName.trim(),email:email.trim().toLowerCase(),phone:cleanPhone(phone),acceptedTerms};const validation={...values,firstNameValid:Boolean(values.firstName),lastNameValid:Boolean(values.lastName),emailValid:/^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(values.email),phoneValid:/^\+?[0-9 ()-]{7,20}$/.test(values.phone)};console.info("[Reservation] validation",validation);const failure=!validation.firstNameValid?"Enter your first name.":!validation.lastNameValid?"Enter your last name.":!validation.emailValid?"Enter a valid email address.":!validation.phoneValid?"Enter a valid phone number, for example +447904443965.":!acceptedTerms?"Please accept the reservation terms.":"";if(failure){setError(failure);return}setBusy(true);setError("");try{const response=await fetch("/api/stripe/create-checkout-session",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({first_name:values.firstName,last_name:values.lastName,email:values.email,phone:values.phone,consent:acceptedTerms,stock_bike_id:bikeId,slug})});const result=await response.json() as {url?:string;error?:string};if(!response.ok||!result.url){setBusy(false);setError(result.error||"Unable to start secure checkout.");return}window.location.assign(result.url)}catch{setBusy(false);setError("Unable to contact secure checkout. Please try again.")}}
  const modal=open?<div className="reservation-modal" role="dialog" aria-modal="true" aria-label={`Reserve ${bike}`} onMouseDown={event=>{if(event.target===event.currentTarget)closeModal()}}><form onSubmit={submit}><header><div><span>SECURE ONLINE RESERVATION</span><h2>Reserve {bike}</h2><p>Pay £99 securely through Stripe. We’ll hold the motorcycle for up to seven days and contact you to complete the purchase.</p></div><button type="button" aria-label="Close" onClick={closeModal} disabled={busy}>×</button></header><div className="reservation-form-grid"><label><span>First name</span><input value={firstName} onChange={event=>setFirstName(event.target.value)} autoComplete="given-name" /></label><label><span>Last name</span><input value={lastName} onChange={event=>setLastName(event.target.value)} autoComplete="family-name" /></label><label><span>Email</span><input value={email} onChange={event=>setEmail(event.target.value)} type="email" autoComplete="email" /></label><label><span>Phone</span><input value={phone} onChange={event=>setPhone(event.target.value)} type="tel" inputMode="tel" autoComplete="tel" /></label><label className="full reservation-consent"><input checked={acceptedTerms} onChange={event=>setAcceptedTerms(event.target.checked)} type="checkbox" /><span>I agree to the <a href="/reserve-online" target="_blank">reservation terms</a>. The £99 fee is deducted from the final purchase price.</span></label>{error&&<p className="full auth-message">{error}</p>}<button className={`full ${busy?"loading":""}`} disabled={busy}>{busy?<><i/>Redirecting to Stripe...</>:"Continue to secure £99 payment"}</button><small className="full">Payment details are entered securely on Stripe. YesMoto does not receive or store your card number.</small></div></form></div>:null;
  return <><button type="button" className={`${className} ${opening?"loading":""}`} onClick={openModal} disabled={opening||busy}>{opening?"Opening reservation...":label}</button>{mounted&&modal?createPortal(modal,document.body):null}</>;
}
