import {NextResponse} from "next/server";import {getSupabaseAdmin} from "@/lib/supabase/admin";import {cleanText,optionalNumber,stockId,uuid} from "@/lib/crm-validation";import {getCurrentUserId} from "@/lib/current-user";
export async function POST(request:Request){try{const body=await request.json() as Record<string,unknown>;const action=cleanText(body.action,50),db=getSupabaseAdmin(),userId=await getCurrentUserId();
  if(action==="createLead"){const customerId=uuid(body.customer_id);if(!customerId)throw new Error("Customer required.");const {data,error}=await db.from("crm_leads").insert({customer_id:customerId,source:"Manual",status:"New",assigned_user_id:userId,created_by:userId,notes:cleanText(body.notes)||null}).select("id").single();if(error)throw error;return NextResponse.json({leadId:data.id})}
  if(action==="assignBike"){const leadId=uuid(body.lead_id),bikeId=stockId(body.stock_bike_id);if(!leadId||!bikeId)throw new Error("Lead and motorcycle required.");const {data:bike,error:bikeError}=await db.from("stock_bikes").select("id,status").eq("id",bikeId).single();if(bikeError)throw bikeError;if(!["in stock","on forecourt","available","prep"].includes(String(bike.status).toLowerCase()))throw new Error("This motorcycle is not available.");const {error}=await db.from("crm_leads").update({preferred_bike_id:bikeId,status:"Qualified"}).eq("id",leadId);if(error)throw error;return NextResponse.json({ok:true})}
  if(action==="reserve"){const customerId=uuid(body.customer_id),leadId=uuid(body.lead_id),bikeId=stockId(body.stock_bike_id);if(!customerId||!leadId||!bikeId)throw new Error("Customer, lead and motorcycle required.");const {data,error}=await db.rpc("crm_reserve_bike",{p_customer_id:customerId,p_lead_id:leadId,p_bike_id:bikeId,p_deposit:optionalNumber(body.deposit_amount)??0,p_expiry:cleanText(body.expires_at),p_method:cleanText(body.method)||"Card",p_receipt:cleanText(body.receipt_number)||null,p_notes:cleanText(body.notes)||null,p_user_id:userId});if(error)throw error;return NextResponse.json({reservationId:data})}
  if(action==="convertSale"){const reservationId=uuid(body.reservation_id);if(!reservationId)throw new Error("Reservation required.");const finance=Boolean(body.finance);const {data,error}=await db.rpc("crm_convert_reservation_to_sale",{p_reservation_id:reservationId,p_finance:finance,p_user_id:userId});if(error)throw error;const saleId=data as string;if(finance){const {error:financeError}=await db.from("crm_finance_applications").insert({customer_id:uuid(body.customer_id),sale_id:saleId,stock_bike_id:stockId(body.stock_bike_id),assigned_user_id:userId,status:cleanText(body.finance_status)||"Draft",lender:cleanText(body.lender)||null,term_months:optionalNumber(body.term_months),apr:optionalNumber(body.apr),deposit:optionalNumber(body.finance_deposit),monthly_payment:optionalNumber(body.monthly_payment)});if(financeError)throw financeError}return NextResponse.json({saleId})}
  if(action==="payment"){const saleId=uuid(body.sale_id),customerId=uuid(body.customer_id),bikeId=stockId(body.stock_bike_id),amount=optionalNumber(body.amount);if(!saleId||!customerId||!bikeId)throw new Error("Sale details missing.");if(!amount||amount<=0)throw new Error("Enter a valid payment amount.");const {data,error}=await db.from("crm_payments").insert({sale_id:saleId,customer_id:customerId,stock_bike_id:bikeId,payment_type:"Payment",method:cleanText(body.method)||"Card",amount,receipt_number:cleanText(body.receipt_number)||null,notes:cleanText(body.notes)||null,created_by:userId}).select("id").single();if(error)throw error;return NextResponse.json({paymentId:data.id})}
  if(action==="delivery"){const saleId=uuid(body.sale_id);if(!saleId)throw new Error("Sale required.");const fields={delivery_method:cleanText(body.delivery_method)||"Collection",scheduled_at:cleanText(body.scheduled_at)||null,identity_checked:Boolean(body.identity_checked),licence_verified:Boolean(body.licence_verified),v5_prepared:Boolean(body.v5_prepared),handover_completed:Boolean(body.handover_completed),keys_given:Boolean(body.keys_given),documents_signed:Boolean(body.documents_signed),photos_taken:Boolean(body.photos_taken),hpi_complete:Boolean(body.hpi_complete),fuel_level:cleanText(body.fuel_level)||null,notes:cleanText(body.notes)||null};const {error}=await db.from("crm_deliveries").update(fields).eq("sale_id",saleId);if(error)throw error;if(Boolean(body.complete)){const completed=await db.rpc("crm_complete_sale",{p_sale_id:saleId,p_user_id:userId});if(completed.error)throw completed.error}return NextResponse.json({ok:true})}
  throw new Error("Unknown workflow action.");
}catch(error){console.error("Sales workflow failed",error);return NextResponse.json({error:error instanceof Error?error.message:"Unable to update sale."},{status:400})}}
