"use client";

import Link from "next/link";
import { useRouter } from "next/navigation";
import { useState } from "react";
import type { SupabaseStockBike } from "@/lib/stock-bike-types";

export function NewStockForm(){const router=useRouter();const [form,setForm]=useState({registration:"",make:"",model:"",year:"",mileage:"",price:"",status:"In Stock"});const [saving,setSaving]=useState(false);const [error,setError]=useState("");const set=(key:keyof typeof form,value:string)=>setForm(current=>({...current,[key]:value}));async function submit(event:React.FormEvent){event.preventDefault();setSaving(true);setError("");try{const response=await fetch("/api/stock",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify(form)});const result=await response.json() as {stock?:SupabaseStockBike;error?:string};if(!response.ok||!result.stock)throw new Error(result.error||"Unable to add stock.");router.push(`/admin/stock/${result.stock.id}`);router.refresh()}catch(caught){setError(caught instanceof Error?caught.message:"Unable to add stock.")}finally{setSaving(false)}}return <div className="admin-page stock-editor"><div className="stock-editor-heading"><div><Link href="/admin/stock">← Stock manager</Link><h1>Add Stock</h1><p>Create a manual stock record. More detail can be added after saving.</p></div></div><section className="stock-editor-panel"><header><div><h2>Motorcycle details</h2><p>Make and model are required.</p></div></header>{error&&<p className="stock-save-message">{error}</p>}<form className="stock-form-grid" onSubmit={submit}><NewField label="Registration" value={form.registration} onChange={value=>set("registration",value)}/><NewField label="Make" value={form.make} onChange={value=>set("make",value)} required/><NewField label="Model" value={form.model} onChange={value=>set("model",value)} required/><NewField label="Year" value={form.year} onChange={value=>set("year",value)} type="number"/><NewField label="Mileage" value={form.mileage} onChange={value=>set("mileage",value)} type="number"/><NewField label="Price" value={form.price} onChange={value=>set("price",value)} type="number"/><label><span>Status</span><select value={form.status} onChange={event=>set("status",event.target.value)}><option>In Stock</option><option>ON FORECOURT</option><option>Prep</option><option>Reserved</option></select></label><div className="full stock-form-actions"><Link href="/admin/stock">Cancel</Link><button className="admin-primary" disabled={saving}>{saving?"Adding stock...":"Add Stock"}</button></div></form></section></div>}
function NewField({label,value,onChange,type="text",required=false}:{label:string;value:string;onChange:(value:string)=>void;type?:string;required?:boolean}){return <label><span>{label}</span><input type={type} required={required} value={value} onChange={event=>onChange(event.target.value)}/></label>}
