"use client";

import Link from "next/link";
import { useMemo, useState } from "react";
import type { SupabaseStockBike } from "@/lib/stock-bike-types";

type Tab="overview"|"photos"|"pricing"|"description"|"dealer5";
const tabs:[Tab,string][]=[["overview","Overview"],["photos","Photos"],["pricing","Pricing"],["description","Description"],["dealer5","Dealer5 Data"]];

export function StockEditor({initialBike}:{initialBike:SupabaseStockBike}){
  const [bike,setBike]=useState(initialBike);const [tab,setTab]=useState<Tab>("overview");const [saving,setSaving]=useState(false);const [message,setMessage]=useState("");
  const [pricingText,setPricingText]=useState(JSON.stringify(initialBike.pricing??{},null,2));
  const [featuresText,setFeaturesText]=useState(JSON.stringify(initialBike.features??[],null,2));
  const images=useMemo(()=>Array.from(new Set([bike.primary_image_url,...bike.image_urls].filter((value):value is string=>Boolean(value)))),[bike.primary_image_url,bike.image_urls]);
  const setField=<K extends keyof SupabaseStockBike>(key:K,value:SupabaseStockBike[K])=>setBike(current=>({...current,[key]:value}));

  async function save(updates:Record<string,unknown>){setSaving(true);setMessage("");try{const response=await fetch(`/api/stock/${bike.id}`,{method:"PATCH",headers:{"Content-Type":"application/json"},body:JSON.stringify(updates)});const result=await response.json() as {stock?:SupabaseStockBike;error?:string};if(!response.ok||!result.stock)throw new Error(result.error||"Unable to save changes.");setBike(result.stock);setMessage("Changes saved.")}catch(error){setMessage(error instanceof Error?error.message:"Unable to save changes.")}finally{setSaving(false)}}
  function saveOverview(){void save({registration:bike.registration,make:bike.make,model:bike.model,variant:bike.variant,year:bike.year,mileage:bike.mileage,colour:bike.colour,engine_cc:bike.engine_cc,vin:bike.vin,status:bike.status,location:bike.location,notes:bike.notes,mot_expiry:bike.mot_expiry,body_style:bike.body_style,fuel:bike.fuel,transmission:bike.transmission})}
  function savePricing(){try{const pricing=JSON.parse(pricingText) as unknown;void save({price:bike.price,vat_status:bike.vat_status,pricing})}catch{setMessage("Pricing JSON is not valid.")}}
  function saveDescription(){try{const features=JSON.parse(featuresText) as unknown;if(!Array.isArray(features))throw new Error();void save({description:bike.description,service_history:bike.service_history,features})}catch{setMessage("Features must be a valid JSON array.")}}

  return <div className="admin-page stock-editor"><div className="stock-editor-heading"><div><Link href="/admin/stock">← Stock manager</Link><h1>{bike.make||"Unknown make"} {bike.model||"Unknown model"}</h1><p>{bike.registration||"Registration pending"} · {bike.stock_number||bike.id}</p></div><span className={`status ${bike.status.toLowerCase().replaceAll(" ","-")}`}>{bike.status}</span></div>
    <nav className="stock-editor-tabs" aria-label="Stock record sections">{tabs.map(([value,label])=><button type="button" className={tab===value?"active":""} onClick={()=>{setTab(value);setMessage("")}} key={value}>{label}{value==="photos"?` (${images.length})`:""}</button>)}</nav>
    {message&&<p className={message==="Changes saved."?"stock-save-message success":"stock-save-message"}>{message}</p>}
    {tab==="overview"&&<EditorPanel title="Stock overview" sub="Core motorcycle and inventory information." onSave={saveOverview} saving={saving}><div className="stock-form-grid"><Field label="Registration" value={bike.registration} onChange={value=>setField("registration",value)}/><Field label="Make" value={bike.make} onChange={value=>setField("make",value)}/><Field label="Model" value={bike.model} onChange={value=>setField("model",value)}/><Field label="Variant" value={bike.variant} onChange={value=>setField("variant",value)}/><NumberField label="Year" value={bike.year} onChange={value=>setField("year",value)}/><NumberField label="Mileage" value={bike.mileage} onChange={value=>setField("mileage",value)}/><Field label="Colour" value={bike.colour} onChange={value=>setField("colour",value)}/><NumberField label="Engine cc" value={bike.engine_cc} onChange={value=>setField("engine_cc",value)}/><Field label="VIN" value={bike.vin} onChange={value=>setField("vin",value)}/><Field label="MOT expiry" value={bike.mot_expiry} onChange={value=>setField("mot_expiry",value)}/><Field label="Body type" value={bike.body_style} onChange={value=>setField("body_style",value)}/><Field label="Fuel" value={bike.fuel} onChange={value=>setField("fuel",value)}/><Field label="Transmission" value={bike.transmission} onChange={value=>setField("transmission",value)}/><label><span>Status</span><select value={bike.status} onChange={event=>setField("status",event.target.value)}><option>In Stock</option><option>ON FORECOURT</option><option>Prep</option><option>Reserved</option><option>Sold</option><option>Sale Completed</option></select></label><Field label="Location" value={bike.location} onChange={value=>setField("location",value)}/><div className="full mapped-stock-fields"><MappedValue label="Registration date" value={bike.registration_date}/><MappedValue label="Previous owners" value={bike.previous_owners}/><MappedValue label="Engine number" value={bike.engine_number}/><MappedValue label="Derivative ID" value={bike.derivative_id}/><MappedValue label="Display status" value={bike.display_status}/><MappedValue label="Attention grabber" value={bike.attention_grabber}/></div><label className="full"><span>Notes</span><textarea rows={6} value={bike.notes??""} onChange={event=>setField("notes",event.target.value)}/></label></div></EditorPanel>}
    {tab==="photos"&&<EditorPanel title="Stock photos" sub="Select the primary image used throughout DealerOS."><div className="stock-photo-gallery">{images.length?images.map(url=><button type="button" className={url===bike.primary_image_url?"primary":""} onClick={()=>void save({primary_image_url:url})} key={url}><img src={url} alt="Stock motorcycle"/><span>{url===bike.primary_image_url?"Primary image":"Set as primary"}</span></button>):<div className="stock-state"><b>No images available</b><span>Images will appear after the Dealer5 sync supplies image URLs.</span></div>}</div></EditorPanel>}
    {tab==="pricing"&&<EditorPanel title="Pricing" sub="Retail price, VAT treatment and Dealer5 pricing payload." onSave={savePricing} saving={saving}><div className="stock-form-grid"><NumberField label="Retail price" value={bike.price} onChange={value=>setField("price",value)}/><Field label="VAT status" value={bike.vat_status} onChange={value=>setField("vat_status",value)}/><label className="full"><span>Pricing JSON</span><textarea className="code-field" rows={16} value={pricingText} onChange={event=>setPricingText(event.target.value)}/></label></div></EditorPanel>}
    {tab==="description"&&<EditorPanel title="Advert description" sub="Customer-facing copy, service history and feature data." onSave={saveDescription} saving={saving}><div className="stock-form-grid"><label className="full"><span>Description</span><textarea rows={10} value={bike.description??""} onChange={event=>setField("description",event.target.value)}/></label><label className="full"><span>Service history</span><textarea rows={6} value={bike.service_history??""} onChange={event=>setField("service_history",event.target.value)}/></label><label className="full"><span>Features JSON</span><textarea className="code-field" rows={12} value={featuresText} onChange={event=>setFeaturesText(event.target.value)}/></label></div></EditorPanel>}
    {tab==="dealer5"&&<EditorPanel title="Dealer5 source data" sub="Read-only source payloads retained for diagnostics."><div className="dealer5-panels"><JsonPanel title="Dealer5 Data" value={bike.dealer5_data}/><JsonPanel title="Specifications" value={bike.specifications}/><JsonPanel title="Features" value={bike.features}/><JsonPanel title="Pricing" value={bike.pricing}/></div></EditorPanel>}
  </div>;
}

function EditorPanel({title,sub,onSave,saving=false,children}:{title:string;sub:string;onSave?:()=>void;saving?:boolean;children:React.ReactNode}){return <section className="stock-editor-panel"><header><div><h2>{title}</h2><p>{sub}</p></div>{onSave&&<button type="button" className="admin-primary" onClick={onSave} disabled={saving}>{saving?"Saving...":"Save changes"}</button>}</header>{children}</section>}
function Field({label,value,onChange}:{label:string;value:string|null;onChange:(value:string)=>void}){return <label><span>{label}</span><input value={value??""} onChange={event=>onChange(event.target.value)}/></label>}
function NumberField({label,value,onChange}:{label:string;value:number|null;onChange:(value:number|null)=>void}){return <label><span>{label}</span><input type="number" value={value??""} onChange={event=>onChange(event.target.value===""?null:Number(event.target.value))}/></label>}
function JsonPanel({title,value}:{title:string;value:unknown}){return <details open><summary>{title}</summary><pre>{JSON.stringify(value??{},null,2)}</pre></details>}
function MappedValue({label,value}:{label:string;value:string|null|undefined}){return <div><span>{label}</span><strong>{value||"—"}</strong></div>}
