"use client";

import Link from "next/link";
import { useRouter } from "next/navigation";
import { useMemo, useState } from "react";
import type { SupabaseStockBike } from "@/lib/stock-bike-types";

type Tab="vehicle"|"pricing"|"advert"|"photos"|"specifications"|"dealer5";
const baseTabs:[Tab,string][]=[["vehicle","Vehicle"],["pricing","Pricing & status"],["advert","Advert content"],["photos","Photos"],["specifications","Specifications"],["dealer5","Dealer5 Data"]];
const advertFields=[['advert_headline','Advert headline'],['intro_description','Intro description'],['key_details','Key details'],['fitted_extras','Fitted extras'],['preparation_work','Preparation & service work'],['included_before_delivery','Included before delivery'],['why_buy_from_yesmoto','Why buy from YesMoto'],['finance_options','Finance options']] as const;

const blank=()=>({id:"new",dealer5_id:null,registration:null,vin:null,make:null,model:null,variant:null,year:null,mileage:null,colour:null,engine_cc:null,price:null,status:"In Stock",advert_title:null,stock_number:null,category:null,body_style:null,fuel:null,transmission:null,description:null,service_history:null,vat_status:null,specifications:{},features:[],pricing:{},dealer5_data:{},dealer5_updated_at:null,source_url:null,image_urls:[],primary_image_url:null,date_in_stock:null,sold_date:null,mot_expiry:null,mot_status:null,workshop_status:null,valeting_status:null,photo_status:null,location:null,notes:null,created_at:"",updated_at:"",plate:null,engine_number:null,number_of_gears:null,previous_owners:null,registration_date:null,display_status:null,show_on_website:false,reserve_enabled:true,reservation_amount:99,advert_sections:{},bhp:null,torque:null,co2:null,road_tax:null,top_speed:null,length_mm:null,width_mm:null,weight_kg:null,euro_emissions:null,hpi_category:null}) as SupabaseStockBike;
const text=(value:unknown)=>typeof value==="string"?value.trim():typeof value==="number"?String(value):"";
const number=(value:unknown)=>{const parsed=Number(text(value).replace(/[^0-9.-]/g,""));return Number.isFinite(parsed)?parsed:null};
function hydrate(input?:SupabaseStockBike){const source=input??blank();const nested=source.dealer5_data&&typeof source.dealer5_data==="object"?(source.dealer5_data as {fields?:unknown}).fields:null;const fields=nested&&typeof nested==="object"&&!Array.isArray(nested)?nested as Record<string,unknown>:{};const pick=(...names:string[])=>{for(const name of names)if(text(fields[name]))return fields[name];return null};return {...blank(),...source,image_urls:Array.isArray(source.image_urls)?source.image_urls.filter((value):value is string=>typeof value==="string"&&Boolean(value.trim())):[],advert_sections:source.advert_sections&&typeof source.advert_sections==="object"&&!Array.isArray(source.advert_sections)?source.advert_sections:{},show_on_website:source.show_on_website??false,reserve_enabled:source.reserve_enabled??true,reservation_amount:source.reservation_amount??99,bhp:source.bhp??number(pick("BHP","Max Power","Power")),torque:(source.torque??text(pick("Max Torque","Torque")))||null,co2:(source.co2??text(pick("CO2","CO2 Emissions")))||null,road_tax:(source.road_tax??text(pick("Road Tax","Tax")))||null,top_speed:(source.top_speed??text(pick("Top Speed")))||null,length_mm:source.length_mm??number(pick("Length")),width_mm:source.width_mm??number(pick("Width")),weight_kg:source.weight_kg??number(pick("Weight","Kerb Weight","Dry Weight")),euro_emissions:(source.euro_emissions??text(pick("Euro Emissions","Euro Status","Emission Class")))||null,service_history:(source.service_history??text(pick("Service History")))||null,hpi_category:(source.hpi_category??text(pick("HPI Category","Insurance Category","Write Off Category","Category ID")))||null} as SupabaseStockBike}

export function StockEditor({initialBike,mode="edit"}:{initialBike?:SupabaseStockBike;mode?:"new"|"edit"}){
  const router=useRouter();const [bike,setBike]=useState(()=>hydrate(initialBike));const [tab,setTab]=useState<Tab>("vehicle");const [saving,setSaving]=useState(false);const [message,setMessage]=useState("");const [newImage,setNewImage]=useState("");const [draggedIndex,setDraggedIndex]=useState<number|null>(null);
  const images=useMemo(()=>Array.from(new Set((bike.image_urls??[]).filter(Boolean))),[bike.image_urls]);const tabs=mode==="new"?baseTabs.filter(([value])=>value!=="dealer5"):baseTabs;
  const setField=<K extends keyof SupabaseStockBike>(key:K,value:SupabaseStockBike[K])=>setBike(current=>({...current,[key]:value}));
  const advert=(key:string)=>typeof (bike.advert_sections??{})[key]==="string"?(bike.advert_sections??{})[key] as string:"";
  const setAdvert=(key:string,value:string)=>setBike(current=>({...current,advert_sections:{...(current.advert_sections??{}),[key]:value}}));
  const fullPayload=()=>{const {id,dealer5_id,dealer5_data,dealer5_updated_at,created_at,updated_at,source_url,stock_number,advert_title,date_in_stock,sold_date,mot_status,workshop_status,valeting_status,photo_status,category,features,pricing,specifications,...editable}=bike;return {...editable,image_urls:images,primary_image_url:bike.primary_image_url||images[0]||null}};
  async function save(updates:Record<string,unknown>=fullPayload()){setSaving(true);setMessage("");try{const creating=mode==="new";const response=await fetch(creating?"/api/stock":`/api/stock/${bike.id}`,{method:creating?"POST":"PATCH",headers:{"Content-Type":"application/json"},body:JSON.stringify(updates)});const result=await response.json() as {stock?:SupabaseStockBike;error?:string};if(!response.ok||!result.stock)throw new Error(result.error||"Unable to save stock advert.");if(creating){router.push(`/admin/stock/${result.stock.id}`);router.refresh();return}setBike(result.stock);setMessage("Changes saved.")}catch(error){setMessage(error instanceof Error?error.message:"Unable to save stock advert.")}finally{setSaving(false)}}
  const move=(index:number,direction:-1|1)=>{const target=index+direction;if(target<0||target>=images.length)return;const next=[...images];[next[index],next[target]]=[next[target],next[index]];setField("image_urls",next);if(!bike.primary_image_url)setField("primary_image_url",next[0])};
  const remove=(url:string)=>{const next=images.filter(image=>image!==url);setField("image_urls",next);if(bike.primary_image_url===url)setField("primary_image_url",next[0]??null)};
  const addImage=()=>{const url=newImage.trim();if(!url)return;const next=Array.from(new Set([...images,url]));setField("image_urls",next);if(!bike.primary_image_url)setField("primary_image_url",next[0]);setNewImage("")};
  const dropAt=(target:number)=>{if(draggedIndex===null||draggedIndex===target)return;const next=[...images];const [moved]=next.splice(draggedIndex,1);next.splice(target,0,moved);setField("image_urls",next);setDraggedIndex(null)};
  const heading=mode==="new"?"Build new stock advert":`${bike.make||"Unknown make"} ${bike.model||"Unknown model"}`;
  return <div className="admin-page stock-editor"><div className="stock-editor-heading"><div><Link href="/admin/stock">← Stock manager</Link><h1>{heading}</h1><p>{mode==="new"?"Complete each section, then create the advert.":`${bike.registration||"Registration pending"} · Full advert editor`}</p></div><button className="admin-primary" onClick={()=>void save()} disabled={saving}>{saving?"Saving...":mode==="new"?"Create advert":"Save all changes"}</button></div>
    <nav className="stock-editor-tabs">{tabs.map(([value,label])=><button type="button" className={tab===value?"active":""} onClick={()=>setTab(value)} key={value}>{label}{value==="photos"?` (${images.length})`:""}</button>)}</nav>{message&&<p className={message==="Changes saved."?"stock-save-message success":"stock-save-message"}>{message}</p>}
    {tab==="vehicle"&&<Panel title="Vehicle" sub="Identity, registration and mechanical details."><div className="stock-form-grid"><Field label="Registration" value={bike.registration} set={v=>setField("registration",v)}/><Field label="Make" value={bike.make} set={v=>setField("make",v)}/><Field label="Model" value={bike.model} set={v=>setField("model",v)}/><Field label="Variant" value={bike.variant} set={v=>setField("variant",v)}/><NumberField label="Year" value={bike.year} set={v=>setField("year",v)}/><Field label="Plate" value={bike.plate} set={v=>setField("plate",v)}/><NumberField label="Mileage" value={bike.mileage} set={v=>setField("mileage",v)}/><Field label="Colour" value={bike.colour} set={v=>setField("colour",v)}/><Field label="Body style" value={bike.body_style} set={v=>setField("body_style",v)}/><NumberField label="Engine cc" value={bike.engine_cc} set={v=>setField("engine_cc",v)}/><Field label="Transmission" value={bike.transmission} set={v=>setField("transmission",v)}/><Field label="Fuel" value={bike.fuel} set={v=>setField("fuel",v)}/><Field label="VIN" value={bike.vin} set={v=>setField("vin",v)}/><Field label="Engine number" value={bike.engine_number} set={v=>setField("engine_number",v)}/><NumberField label="Number of gears" value={bike.number_of_gears} set={v=>setField("number_of_gears",v)}/><NumberField label="Previous owners" value={bike.previous_owners} set={v=>setField("previous_owners",v)}/><DateField label="MOT expiry" value={bike.mot_expiry} set={v=>setField("mot_expiry",v)}/><DateField label="Registration date" value={bike.registration_date} set={v=>setField("registration_date",v)}/></div></Panel>}
    {tab==="pricing"&&<Panel title="Pricing & status" sub="Control retail price, availability and website publishing."><div className="stock-form-grid"><NumberField label="Retail price" value={bike.price} set={v=>setField("price",v)}/><Field label="VAT status" value={bike.vat_status} set={v=>setField("vat_status",v)}/><SelectField label="Status" value={bike.status} set={v=>setField("status",v)} options={["In Stock","ON FORECOURT","Prep","Reserved","Sold","Sale Completed"]}/><Field label="Display status" value={bike.display_status} set={v=>setField("display_status",v)}/><ToggleField label="Show on website" value={bike.show_on_website} set={v=>setField("show_on_website",v)}/><ToggleField label="Reserve enabled" value={bike.reserve_enabled} set={v=>setField("reserve_enabled",v)}/><NumberField label="Reservation amount" value={bike.reservation_amount} set={v=>setField("reservation_amount",v??99)}/></div></Panel>}
    {tab==="advert"&&<Panel title="Advert content" sub="Structured customer-facing sections used by the public advert."><div className="stock-form-grid advert-builder-fields">{advertFields.map(([key,label])=><label className="full" key={key}><span>{label}</span><textarea rows={key==="intro_description"?7:5} value={advert(key)} onChange={event=>setAdvert(key,event.target.value)}/></label>)}</div></Panel>}
    {tab==="photos"&&<Panel title="Photos" sub="Drag photos into the order you want. The main image is highlighted."><div className="photo-url-adder"><input value={newImage} onChange={event=>setNewImage(event.target.value)} placeholder="https://... image URL"/><button type="button" onClick={addImage}>Add Image URL</button></div><div className="photo-manager-help"><b>Drag and drop to reorder</b><span>Changes remain local until you click Save photo order.</span></div><div className="stock-photo-manager shopify-photo-grid">{images.map((url,index)=><article draggable onDragStart={()=>setDraggedIndex(index)} onDragEnd={()=>setDraggedIndex(null)} onDragOver={event=>event.preventDefault()} onDrop={()=>dropAt(index)} className={`${url===bike.primary_image_url?"main":""} ${draggedIndex===index?"dragging":""}`} key={url}><div className="photo-drag-handle" title="Drag to reorder">⋮⋮</div><img src={url} alt={`Stock motorcycle photo ${index+1}`}/><div className="photo-card-copy"><b>{url===bike.primary_image_url?"Main image":`Photo ${index+1}`}</b><span>{url}</span><nav><button type="button" onClick={()=>move(index,-1)} disabled={index===0} aria-label="Move photo up">↑</button><button type="button" onClick={()=>move(index,1)} disabled={index===images.length-1} aria-label="Move photo down">↓</button><button type="button" onClick={()=>setField("primary_image_url",url)}>Set Main</button><button type="button" className="danger" onClick={()=>remove(url)}>Delete</button></nav></div></article>)}</div><div className="photo-save"><button className="admin-primary" type="button" onClick={()=>void save({image_urls:images,primary_image_url:bike.primary_image_url||images[0]||null})}>Save photo order</button></div></Panel>}
    {tab==="specifications"&&<Panel title="Specifications" sub="Customer-facing performance and technical information."><div className="stock-form-grid"><NumberField label="BHP" value={bike.bhp} set={v=>setField("bhp",v)}/><Field label="Torque" value={bike.torque} set={v=>setField("torque",v)}/><Field label="CO2" value={bike.co2} set={v=>setField("co2",v)}/><Field label="Road tax" value={bike.road_tax} set={v=>setField("road_tax",v)}/><Field label="Top speed" value={bike.top_speed} set={v=>setField("top_speed",v)}/><NumberField label="Length mm" value={bike.length_mm} set={v=>setField("length_mm",v)}/><NumberField label="Width mm" value={bike.width_mm} set={v=>setField("width_mm",v)}/><NumberField label="Weight kg" value={bike.weight_kg} set={v=>setField("weight_kg",v)}/><Field label="Euro emissions" value={bike.euro_emissions} set={v=>setField("euro_emissions",v)}/><label className="full"><span>Service history</span><textarea rows={6} value={bike.service_history??""} onChange={event=>setField("service_history",event.target.value)}/></label><Field label="HPI / write-off category" value={bike.hpi_category} set={v=>setField("hpi_category",v)}/></div></Panel>}
    {tab==="dealer5"&&<Panel title="Dealer5 Data" sub="Read-only source data for diagnostics."><div className="dealer5-panels"><Json title="Dealer5 Data" value={bike.dealer5_data}/><Json title="Specifications" value={bike.specifications}/><Json title="Features" value={bike.features}/><Json title="Pricing" value={bike.pricing}/></div></Panel>}
  </div>;
}

function Panel({title,sub,children}:{title:string;sub:string;children:React.ReactNode}){return <section className="stock-editor-panel"><header><div><h2>{title}</h2><p>{sub}</p></div></header>{children}</section>}
function Field({label,value,set}:{label:string;value:string|null|undefined;set:(v:string)=>void}){return <label><span>{label}</span><input value={value??""} onChange={e=>set(e.target.value)}/></label>}
function DateField({label,value,set}:{label:string;value:string|null;set:(v:string)=>void}){return <label><span>{label}</span><input type="date" value={value?.slice(0,10)??""} onChange={e=>set(e.target.value)}/></label>}
function NumberField({label,value,set}:{label:string;value:number|null;set:(v:number|null)=>void}){return <label><span>{label}</span><input type="number" value={value??""} onChange={e=>set(e.target.value===""?null:Number(e.target.value))}/></label>}
function SelectField({label,value,set,options}:{label:string;value:string;set:(v:string)=>void;options:string[]}){return <label><span>{label}</span><select value={value} onChange={e=>set(e.target.value)}>{options.map(option=><option key={option}>{option}</option>)}</select></label>}
function ToggleField({label,value,set}:{label:string;value:boolean;set:(v:boolean)=>void}){return <label className="builder-toggle"><span>{label}</span><input type="checkbox" checked={value} onChange={e=>set(e.target.checked)}/><b>{value?"Yes":"No"}</b></label>}
function Json({title,value}:{title:string;value:unknown}){return <details open><summary>{title}</summary><pre>{JSON.stringify(value??{},null,2)}</pre></details>}
