-- Opportunity comparable adverts used by the scanner calculation.
-- This migration does not alter buying_opportunities or user-managed fields.

create table if not exists public.opportunity_comparables (
  id bigint generated by default as identity primary key,
  opportunity_listing_id bigint not null,
  comparable_listing_id bigint,
  make text,
  model text,
  year bigint,
  mileage bigint,
  price text,
  seller_type text,
  advert_url text,
  dealer_name text,
  distance text,
  created_at timestamptz default now()
);

create index if not exists opportunity_comparables_opportunity_listing_id_idx
  on public.opportunity_comparables (opportunity_listing_id);

alter table public.opportunity_comparables enable row level security;
revoke all on table public.opportunity_comparables from public, anon, authenticated;
revoke all on sequence public.opportunity_comparables_id_seq from public, anon, authenticated;
grant all on table public.opportunity_comparables to service_role;
grant all on sequence public.opportunity_comparables_id_seq to service_role;

-- Scanner contract: call once per opportunity with the exact comparable rows
-- used for its median/profit calculation. The replacement is one transaction.
create or replace function public.replace_opportunity_comparables(
  p_opportunity_listing_id bigint,
  p_comparables jsonb
)
returns integer
language plpgsql
security invoker
set search_path = public
as $$
declare
  inserted_count integer;
begin
  if p_opportunity_listing_id is null then
    raise exception 'An opportunity listing ID is required';
  end if;

  if p_comparables is null or jsonb_typeof(p_comparables) <> 'array' then
    raise exception 'Comparables must be supplied as a JSON array';
  end if;

  delete from public.opportunity_comparables
  where opportunity_listing_id = p_opportunity_listing_id;

  insert into public.opportunity_comparables (
    opportunity_listing_id,
    comparable_listing_id,
    make,
    model,
    year,
    mileage,
    price,
    seller_type,
    advert_url,
    dealer_name,
    distance
  )
  select
    p_opportunity_listing_id,
    comparable.comparable_listing_id,
    comparable.make,
    comparable.model,
    comparable.year,
    comparable.mileage,
    comparable.price,
    comparable.seller_type,
    comparable.advert_url,
    comparable.dealer_name,
    comparable.distance
  from jsonb_to_recordset(p_comparables) as comparable (
    comparable_listing_id bigint,
    make text,
    model text,
    year bigint,
    mileage bigint,
    price text,
    seller_type text,
    advert_url text,
    dealer_name text,
    distance text
  );

  get diagnostics inserted_count = row_count;
  return inserted_count;
end;
$$;

revoke all on function public.replace_opportunity_comparables(bigint, jsonb)
  from public, anon, authenticated;
grant execute on function public.replace_opportunity_comparables(bigint, jsonb)
  to service_role;

comment on function public.replace_opportunity_comparables(bigint, jsonb) is
  'Scanner-only atomic replacement of comparable adverts used for one opportunity calculation.';

-- Python/Supabase scanner call after calculating the median:
-- await supabase.rpc("replace_opportunity_comparables", {
--     "p_opportunity_listing_id": opportunity_listing_id,
--     "p_comparables": comparables_used_for_median,
-- }).execute()
