create table if not exists public.retail_checks (
  id bigint generated by default as identity primary key,
  "Registration" text,
  "Make" text,
  "Model" text,
  "Year" text,
  "Mileage" text,
  "Asking Price" text,
  "Status" text not null default 'Pending',
  "Market Retail" numeric,
  "Fast Sale Retail" numeric,
  "Premium Retail" numeric,
  "Available Margin" numeric,
  "Suggested Offer" numeric,
  "Target Profit" numeric,
  "Comparable Count" integer,
  "Comparable Summary" text,
  "Confidence" text,
  "Opportunity Score" numeric,
  "Buy Decision" text,
  "Percayso Retail" numeric,
  "Percayso Trade" numeric,
  "Percayso Independent" numeric,
  "Percayso Franchise" numeric,
  "Percayso Days To Sale" text,
  "Last Checked" timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index if not exists retail_checks_created_at_idx on public.retail_checks (created_at desc);
create index if not exists retail_checks_registration_idx on public.retail_checks ("Registration");
alter table public.retail_checks enable row level security;
revoke all on table public.retail_checks from public, anon, authenticated;
revoke all on sequence public.retail_checks_id_seq from public, anon, authenticated;
grant all on table public.retail_checks to service_role;
grant all on sequence public.retail_checks_id_seq to service_role;
