-- Opportunity Tracker V2 user-managed fields, scanner protection, and activity.
-- Existing market/scanner columns are deliberately left untouched.

alter table public.buying_opportunities
  add column if not exists seen boolean not null default false,
  add column if not exists notes text,
  add column if not exists status text default 'New',
  add column if not exists favourite boolean not null default false,
  add column if not exists hidden boolean not null default false,
  add column if not exists last_seen timestamptz,
  add column if not exists updated_at timestamptz default now();

-- Remove the earlier V2 constraint before converting its values.
alter table public.buying_opportunities
  drop constraint if exists buying_opportunities_status_check;

-- "Seen" is now a workflow status. Preserve any state captured by the earlier
-- checkbox model when this migration is run over an existing V2 table.
update public.buying_opportunities
set status = 'Seen'
where seen = true and coalesce(status, 'New') = 'New';

-- Convert the former overlapping Hidden status into the dedicated visibility
-- flag before narrowing status to workflow-only values.
update public.buying_opportunities
set hidden = true, status = 'New'
where status = 'Hidden';

alter table public.buying_opportunities
  add constraint buying_opportunities_status_check
  check (
    status is null or status in (
      'New',
      'Seen',
      'Researching',
      'Contacted',
      'Negotiating',
      'Purchased',
      'Rejected'
    )
  );

comment on column public.buying_opportunities.seen is
  'Deprecated UI field retained for compatibility. Workflow state now uses status.';
comment on column public.buying_opportunities.notes is
  'User-managed. The opportunity scanner must never update this column.';
comment on column public.buying_opportunities.status is
  'User-managed workflow state. The opportunity scanner must never update this column.';
comment on column public.buying_opportunities.favourite is
  'User-managed. The opportunity scanner must never update this column.';
comment on column public.buying_opportunities.hidden is
  'User-managed. The opportunity scanner must never update this column.';
comment on column public.buying_opportunities.last_seen is
  'Automatically refreshed whenever the scanner inserts or updates an opportunity.';

create table if not exists public.opportunity_activity (
  id bigint generated by default as identity primary key,
  listing_id bigint not null,
  activity_type text not null,
  description text not null,
  metadata jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now()
);

create index if not exists opportunity_activity_listing_created_idx
  on public.opportunity_activity (listing_id, created_at desc);

alter table public.opportunity_activity enable row level security;
revoke all on table public.opportunity_activity from public, anon, authenticated;
revoke all on sequence public.opportunity_activity_id_seq from public, anon, authenticated;
grant all on table public.opportunity_activity to service_role;
grant all on sequence public.opportunity_activity_id_seq to service_role;

-- Scanner inserts/updates refresh last_seen automatically. Scanner updates are
-- also prevented from changing user-managed fields, even if a legacy payload
-- accidentally includes them.
create or replace function public.protect_opportunity_user_fields()
returns trigger
language plpgsql
set search_path = public
as $$
begin
  if tg_op = 'INSERT' then
    new.last_seen := coalesce(new.last_seen, now());
    return new;
  end if;

  if current_setting('yesmoto.allow_user_field_update', true) is distinct from 'on' then
    new.seen := old.seen;
    new.notes := old.notes;
    new.status := old.status;
    new.favourite := old.favourite;
    new.hidden := old.hidden;
    new.updated_at := old.updated_at;
    new.last_seen := now();
  end if;

  return new;
end;
$$;

drop trigger if exists preserve_opportunity_user_fields on public.buying_opportunities;
drop trigger if exists protect_opportunity_user_fields on public.buying_opportunities;
drop function if exists public.preserve_opportunity_user_fields();
create trigger protect_opportunity_user_fields
before insert or update on public.buying_opportunities
for each row
execute function public.protect_opportunity_user_fields();

-- Record scanner-created opportunities and asking-price reductions.
create or replace function public.log_opportunity_market_activity()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
declare
  old_price_text text;
  new_price_text text;
  old_price numeric;
  new_price numeric;
begin
  if tg_op = 'INSERT' then
    insert into public.opportunity_activity (listing_id, activity_type, description)
    values (new."Listing ID", 'created', 'Created');
    return null;
  end if;

  if current_setting('yesmoto.allow_user_field_update', true) = 'on' then
    return null;
  end if;

  old_price_text := regexp_replace(coalesce(old."Asking Price"::text, ''), '[^0-9.-]', '', 'g');
  new_price_text := regexp_replace(coalesce(new."Asking Price"::text, ''), '[^0-9.-]', '', 'g');

  if old_price_text ~ '^-?[0-9]+(\.[0-9]+)?$' then old_price := old_price_text::numeric; end if;
  if new_price_text ~ '^-?[0-9]+(\.[0-9]+)?$' then new_price := new_price_text::numeric; end if;

  if old_price is not null and new_price is not null and new_price < old_price then
    insert into public.opportunity_activity (
      listing_id,
      activity_type,
      description,
      metadata
    ) values (
      new."Listing ID",
      'price_reduced',
      'Price reduced from ' || old."Asking Price"::text || ' to ' || new."Asking Price"::text,
      jsonb_build_object('from', old."Asking Price", 'to', new."Asking Price")
    );
  end if;

  return null;
end;
$$;

drop trigger if exists log_opportunity_market_activity on public.buying_opportunities;
create trigger log_opportunity_market_activity
after insert or update on public.buying_opportunities
for each row
execute function public.log_opportunity_market_activity();

-- This function is callable only with the server-side service-role key. The
-- browser talks to the authenticated Next.js route and never receives that key.
create or replace function public.update_buying_opportunity_user_fields(
  p_listing_id bigint,
  p_patch jsonb
)
returns setof public.buying_opportunities
language plpgsql
security invoker
set search_path = public
as $$
declare
  previous public.buying_opportunities%rowtype;
begin
  if p_patch is null or p_patch = '{}'::jsonb then
    raise exception 'At least one user-managed field is required';
  end if;

  if exists (
    select 1
    from jsonb_object_keys(p_patch) as supplied(key)
    where supplied.key not in ('notes', 'status', 'favourite', 'hidden')
  ) then
    raise exception 'Unsupported opportunity field';
  end if;

  select * into previous
  from public.buying_opportunities
  where "Listing ID" = p_listing_id;

  if not found then return; end if;

  perform set_config('yesmoto.allow_user_field_update', 'on', true);

  return query
  update public.buying_opportunities
  set
    notes = case when p_patch ? 'notes' then p_patch ->> 'notes' else notes end,
    status = case when p_patch ? 'status' then p_patch ->> 'status' else status end,
    favourite = case when p_patch ? 'favourite' then (p_patch ->> 'favourite')::boolean else favourite end,
    hidden = case when p_patch ? 'hidden' then (p_patch ->> 'hidden')::boolean else hidden end,
    updated_at = now()
  where "Listing ID" = p_listing_id
  returning *;

  if p_patch ? 'status' and previous.status is distinct from (p_patch ->> 'status') then
    insert into public.opportunity_activity (listing_id, activity_type, description, metadata)
    values (
      p_listing_id,
      'status_changed',
      'Status changed to ' || (p_patch ->> 'status'),
      jsonb_build_object('from', previous.status, 'to', p_patch ->> 'status')
    );
  end if;

  if p_patch ? 'notes' and previous.notes is distinct from (p_patch ->> 'notes') then
    insert into public.opportunity_activity (listing_id, activity_type, description)
    values (
      p_listing_id,
      'note_updated',
      case when nullif(previous.notes, '') is null then 'Added note' else 'Updated note' end
    );
  end if;

  if p_patch ? 'favourite' and previous.favourite is distinct from (p_patch ->> 'favourite')::boolean then
    insert into public.opportunity_activity (listing_id, activity_type, description)
    values (
      p_listing_id,
      'favourite_changed',
      case when (p_patch ->> 'favourite')::boolean then 'Added to favourites' else 'Removed from favourites' end
    );
  end if;

  if p_patch ? 'hidden' and previous.hidden is distinct from (p_patch ->> 'hidden')::boolean then
    insert into public.opportunity_activity (listing_id, activity_type, description)
    values (
      p_listing_id,
      'visibility_changed',
      case when (p_patch ->> 'hidden')::boolean then 'Hidden' else 'Restored' end
    );
  end if;
end;
$$;

create or replace function public.log_buying_opportunity_viewed(p_listing_id bigint)
returns void
language sql
security invoker
set search_path = public
as $$
  insert into public.opportunity_activity (listing_id, activity_type, description)
  select p_listing_id, 'viewed', 'Viewed'
  where exists (
    select 1 from public.buying_opportunities where "Listing ID" = p_listing_id
  );
$$;

revoke all on function public.update_buying_opportunity_user_fields(bigint, jsonb) from public, anon, authenticated;
revoke all on function public.log_buying_opportunity_viewed(bigint) from public, anon, authenticated;
grant execute on function public.update_buying_opportunity_user_fields(bigint, jsonb) to service_role;
grant execute on function public.log_buying_opportunity_viewed(bigint) to service_role;

-- Scanner compatibility:
-- The trigger now sets last_seen = now() for every scanner insert/update. Keep
-- the scanner upsert itself limited to these market-owned fields:
--   Score, Asking Price, Potential Margin, Dealer Median, Comparable Count,
--   Days Live, Advert URL, and last_seen.
-- User fields remain protected even if a legacy scanner payload includes them.
