create table if not exists public.website_leads (
  id bigint generated by default as identity primary key,
  public_id uuid not null default gen_random_uuid(),
  external_submission_id text,
  lead_source text,
  form_name text,
  owner text,
  reg text,
  make text,
  model text,
  year text,
  engine text,
  colour text,
  mileage text,
  owners text,
  spare_keys text,
  bike_condition text,
  damage text,
  history text,
  service text,
  mot text,
  extras text,
  price text,
  finance_information text,
  customer_message text,
  fname text,
  lname text,
  email text,
  phone text,
  postcode text,
  image1 text,
  image2 text,
  image3 text,
  image4 text,
  image5 text,
  image6 text,
  image7 text,
  image8 text,
  image9 text,
  image10 text,
  website text,
  date timestamptz,
  "Images" text,
  valuation_status text default 'pending',
  retail_estimate numeric(12,2),
  suggested_offer numeric(12,2),
  estimated_margin numeric(12,2),
  similar_bikes text,
  auto_trader_search text,
  valuation_notes text,
  "Motorway output" text,
  images text[],
  status text not null default 'new',
  assigned_to text,
  contacted_at timestamptz,
  offer_made_at timestamptz,
  purchased_at timestamptz,
  internal_notes text,
  raw_payload jsonb not null default '{}'::jsonb,
  consent_marketing boolean,
  consent_terms boolean,
  consent_source text,
  submitted_at timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

alter table public.website_leads
  add column if not exists public_id uuid not null default gen_random_uuid(),
  add column if not exists external_submission_id text,
  add column if not exists lead_source text,
  add column if not exists form_name text,
  add column if not exists finance_information text,
  add column if not exists customer_message text,
  add column if not exists raw_payload jsonb not null default '{}'::jsonb,
  add column if not exists consent_marketing boolean,
  add column if not exists consent_terms boolean,
  add column if not exists consent_source text,
  add column if not exists submitted_at timestamptz;

update public.website_leads
set
  lead_source = coalesce(lead_source, case
    when website = 'bikebuyeruk' then 'bike_buyer_uk'
    when website = 'sellyourmotorbike' then 'sell_your_motorbike'
    else website
  end),
  submitted_at = coalesce(
    submitted_at,
    case
      when nullif(date::text, '') ~ '^\d{4}-\d{2}-\d{2}' then nullif(date::text, '')::timestamptz
      else null
    end,
    created_at
  ),
  external_submission_id = coalesce(external_submission_id, 'legacy-airtable-' || id::text)
where external_submission_id is null or lead_source is null or submitted_at is null;

create unique index if not exists website_leads_public_id_unique_idx
  on public.website_leads(public_id);

create unique index if not exists website_leads_external_submission_unique_idx
  on public.website_leads(lead_source, external_submission_id)
  where lead_source is not null and external_submission_id is not null;

create index if not exists website_leads_submitted_at_idx
  on public.website_leads(submitted_at desc);

create index if not exists website_leads_source_status_idx
  on public.website_leads(lead_source, status, submitted_at desc);

create index if not exists website_leads_raw_payload_gin_idx
  on public.website_leads using gin(raw_payload);

alter table public.website_leads enable row level security;

drop policy if exists "Authenticated staff read website leads" on public.website_leads;
create policy "Authenticated staff read website leads"
  on public.website_leads for select to authenticated
  using(public.crm_staff_can_access());

drop policy if exists "Authenticated staff manage website leads" on public.website_leads;
create policy "Authenticated staff manage website leads"
  on public.website_leads for all to authenticated
  using(public.crm_staff_can_access())
  with check(public.crm_staff_can_access());

revoke insert on public.website_leads from anon;

drop trigger if exists set_website_leads_updated_at on public.website_leads;
create trigger set_website_leads_updated_at
  before update on public.website_leads
  for each row execute function public.crm_set_updated_at();
