alter table public.crm_customers add column if not exists house_name_number text;
alter table public.crm_customers add column if not exists street text;
alter table public.crm_customers add column if not exists address_line_3 text;
alter table public.crm_customers add column if not exists country text default 'United Kingdom';
alter table public.crm_customers add column if not exists latitude numeric(10,7);
alter table public.crm_customers add column if not exists longitude numeric(10,7);
alter table public.crm_customers add column if not exists customer_status text not null default 'Prospect';

alter table public.crm_reservations add column if not exists cancelled_at timestamptz;
alter table public.crm_reservations add column if not exists cancellation_reason text;
alter table public.crm_sales add column if not exists invoice_number text;
alter table public.crm_sales add column if not exists part_exchange_amount numeric(12,2) not null default 0;

create or replace function public.crm_sync_reservation_stock() returns trigger language plpgsql security definer set search_path='' as $$
begin if new.status in ('Active','Deposit Taken') then if exists(select 1 from public.crm_reservations r where r.stock_bike_id=new.stock_bike_id and r.id<>new.id and r.status in ('Active','Deposit Taken')) then raise exception 'This motorcycle already has an active reservation'; end if; if exists(select 1 from public.stock_bikes b where b.id=new.stock_bike_id and lower(b.status) in ('sold','sale completed','delivered','archived')) then raise exception 'This motorcycle is not available to reserve'; end if; update public.stock_bikes set status='Reserved' where id=new.stock_bike_id; elsif tg_op='UPDATE' and old.status in ('Active','Deposit Taken') and new.status in ('Expired','Cancelled','Refunded') then update public.stock_bikes set status='In Stock' where id=new.stock_bike_id and lower(status)='reserved'; end if; return new; end $$;

create table if not exists public.crm_payments (
  id uuid primary key default gen_random_uuid(), customer_id uuid not null references public.crm_customers(id) on delete restrict,
  sale_id uuid references public.crm_sales(id) on delete restrict, reservation_id uuid references public.crm_reservations(id) on delete restrict,
  stock_bike_id bigint references public.stock_bikes(id) on delete restrict, payment_type text not null default 'Payment',
  method text not null, amount numeric(12,2) not null, receipt_number text, paid_at timestamptz not null default now(), notes text,
  status text not null default 'Completed', created_by uuid references public.dealer_users(id) on delete set null,
  created_at timestamptz not null default now(), updated_at timestamptz not null default now(), deleted_at timestamptz,
  constraint crm_payment_amount check(amount>0), constraint crm_payment_method check(method in ('Cash','Card','Bank','Finance','Finance Deposit','Part Exchange','Mixed')),
  constraint crm_payment_parent check(num_nonnulls(sale_id,reservation_id)>=1)
);
create index if not exists crm_payments_sale_idx on public.crm_payments(sale_id,paid_at);

create table if not exists public.crm_invoices (
  id uuid primary key default gen_random_uuid(), invoice_number text not null unique, sale_id uuid not null unique references public.crm_sales(id) on delete restrict,
  customer_id uuid not null references public.crm_customers(id) on delete restrict, stock_bike_id bigint not null references public.stock_bikes(id) on delete restrict,
  subtotal numeric(12,2) not null, total numeric(12,2) not null, paid numeric(12,2) not null default 0, balance numeric(12,2) not null,
  status text not null default 'Open', issued_at timestamptz not null default now(), due_at timestamptz, metadata jsonb not null default '{}',
  created_at timestamptz not null default now(), updated_at timestamptz not null default now(), deleted_at timestamptz
);

create table if not exists public.crm_deliveries (
  id uuid primary key default gen_random_uuid(), sale_id uuid not null unique references public.crm_sales(id) on delete restrict,
  customer_id uuid not null references public.crm_customers(id) on delete restrict, stock_bike_id bigint not null references public.stock_bikes(id) on delete restrict,
  delivery_method text not null default 'Collection', scheduled_at timestamptz, completed_at timestamptz, status text not null default 'Pending',
  identity_checked boolean not null default false, licence_verified boolean not null default false, v5_prepared boolean not null default false,
  handover_completed boolean not null default false, keys_given boolean not null default false, documents_signed boolean not null default false,
  photos_taken boolean not null default false, hpi_complete boolean not null default false, fuel_level text, notes text,
  assigned_user_id uuid references public.dealer_users(id) on delete set null, created_at timestamptz not null default now(), updated_at timestamptz not null default now(), deleted_at timestamptz
);

create or replace function public.crm_refresh_sale_balance(p_sale_id uuid) returns void language plpgsql security definer set search_path='' as $$
declare total_paid numeric; begin select coalesce(sum(amount),0) into total_paid from public.crm_payments where sale_id=p_sale_id and status='Completed' and deleted_at is null; update public.crm_sales set balance_due=greatest(coalesce(sale_price,0)-coalesce(part_exchange_amount,0)-total_paid,0),payment_status=case when total_paid+coalesce(part_exchange_amount,0)>=coalesce(sale_price,0) then 'Paid' when total_paid>0 then 'Part Paid' else 'Unpaid' end where id=p_sale_id; update public.crm_invoices set paid=total_paid,balance=greatest(total-coalesce((select part_exchange_amount from public.crm_sales where id=p_sale_id),0)-total_paid,0),status=case when total_paid+coalesce((select part_exchange_amount from public.crm_sales where id=p_sale_id),0)>=total then 'Paid' else 'Open' end where sale_id=p_sale_id; end $$;
create or replace function public.crm_payment_changed() returns trigger language plpgsql security definer set search_path='' as $$ begin perform public.crm_refresh_sale_balance(coalesce(new.sale_id,old.sale_id)); return coalesce(new,old); end $$;
drop trigger if exists refresh_sale_balance on public.crm_payments;
create trigger refresh_sale_balance after insert or update or delete on public.crm_payments for each row execute function public.crm_payment_changed();

create or replace function public.crm_reserve_bike(p_customer_id uuid,p_lead_id uuid,p_bike_id bigint,p_deposit numeric,p_expiry timestamptz,p_method text,p_receipt text,p_notes text,p_user_id uuid default null) returns uuid language plpgsql security definer set search_path='' as $$
declare bike public.stock_bikes%rowtype; reservation_id uuid; begin select * into bike from public.stock_bikes where id=p_bike_id for update; if not found then raise exception 'Motorcycle not found'; end if; if lower(bike.status) not in ('in stock','on forecourt','available','prep') then raise exception 'Motorcycle is not available'; end if; if exists(select 1 from public.crm_reservations where stock_bike_id=p_bike_id and status in ('Active','Deposit Taken')) then raise exception 'Motorcycle is already reserved'; end if; insert into public.crm_reservations(customer_id,lead_id,stock_bike_id,deposit_amount,expires_at,status,notes,assigned_user_id,created_by) values(p_customer_id,p_lead_id,p_bike_id,coalesce(p_deposit,0),p_expiry,case when coalesce(p_deposit,0)>0 then 'Deposit Taken' else 'Active' end,p_notes,p_user_id,p_user_id) returning id into reservation_id; if coalesce(p_deposit,0)>0 then insert into public.crm_payments(customer_id,reservation_id,stock_bike_id,payment_type,method,amount,receipt_number,created_by) values(p_customer_id,reservation_id,p_bike_id,'Deposit',coalesce(p_method,'Card'),p_deposit,p_receipt,p_user_id); end if; update public.crm_leads set customer_id=p_customer_id,preferred_bike_id=p_bike_id,status='Reserved',assigned_user_id=coalesce(assigned_user_id,p_user_id) where id=p_lead_id; insert into public.crm_activities(activity_type,subject,body,status,customer_id,lead_id,reservation_id,stock_bike_id,created_by) values('Note','Reservation created',p_notes,'Completed',p_customer_id,p_lead_id,reservation_id,p_bike_id,p_user_id); return reservation_id; end $$;

create or replace function public.crm_convert_reservation_to_sale(p_reservation_id uuid,p_finance boolean default false,p_user_id uuid default null) returns uuid language plpgsql security definer set search_path='' as $$
declare r public.crm_reservations%rowtype; bike public.stock_bikes%rowtype; v_sale_id uuid; inv text; deposit_paid numeric; begin select * into r from public.crm_reservations where id=p_reservation_id for update; if not found or r.status not in ('Active','Deposit Taken') then raise exception 'Active reservation not found'; end if; select * into bike from public.stock_bikes where id=r.stock_bike_id for update; if exists(select 1 from public.crm_sales where stock_bike_id=r.stock_bike_id and status not in ('Completed','Cancelled')) then raise exception 'Motorcycle already has an active sale'; end if; select coalesce(sum(amount),0) into deposit_paid from public.crm_payments where reservation_id=r.id and status='Completed'; inv='YM-'||to_char(now(),'YYYYMM')||'-'||upper(substr(replace(gen_random_uuid()::text,'-',''),1,6)); insert into public.crm_sales(customer_id,stock_bike_id,lead_id,reservation_id,assigned_user_id,status,sale_price,deposit_amount,balance_due,payment_status,invoice_number,created_by) values(r.customer_id,r.stock_bike_id,r.lead_id,r.id,coalesce(r.assigned_user_id,p_user_id),case when p_finance then 'Finance' else 'Awaiting Payment' end,bike.price,deposit_paid,greatest(coalesce(bike.price,0)-deposit_paid,0),case when deposit_paid>0 then 'Part Paid' else 'Unpaid' end,inv,p_user_id) returning id into v_sale_id; update public.crm_payments set sale_id=v_sale_id where reservation_id=r.id; update public.crm_reservations set status='Converted' where id=r.id; update public.crm_leads set status='Negotiation' where id=r.lead_id; insert into public.crm_invoices(invoice_number,sale_id,customer_id,stock_bike_id,subtotal,total,paid,balance) values(inv,v_sale_id,r.customer_id,r.stock_bike_id,coalesce(bike.price,0),coalesce(bike.price,0),deposit_paid,greatest(coalesce(bike.price,0)-deposit_paid,0)); insert into public.crm_deliveries(sale_id,customer_id,stock_bike_id,assigned_user_id) values(v_sale_id,r.customer_id,r.stock_bike_id,coalesce(r.assigned_user_id,p_user_id)); insert into public.crm_activities(activity_type,subject,status,customer_id,lead_id,reservation_id,stock_bike_id,sale_id,created_by) values('Note','Sale created','Completed',r.customer_id,r.lead_id,r.id,r.stock_bike_id,v_sale_id,p_user_id); return v_sale_id; end $$;

create or replace function public.crm_complete_sale(p_sale_id uuid,p_user_id uuid default null) returns void language plpgsql security definer set search_path='' as $$
declare s public.crm_sales%rowtype; d public.crm_deliveries%rowtype; begin perform public.crm_refresh_sale_balance(p_sale_id); select * into s from public.crm_sales where id=p_sale_id for update; select * into d from public.crm_deliveries where sale_id=p_sale_id for update; if s.balance_due>0 then raise exception 'Outstanding balance remains'; end if; if not(d.identity_checked and d.licence_verified and d.v5_prepared and d.handover_completed and d.keys_given and d.documents_signed and d.hpi_complete) then raise exception 'Delivery checklist is incomplete'; end if; update public.crm_sales set status='Completed',completed_at=now(),delivery_date=current_date where id=p_sale_id; update public.crm_deliveries set status='Completed',completed_at=now() where id=d.id; update public.stock_bikes set status='Sold',sold_date=current_date where id=s.stock_bike_id; update public.crm_customers set customer_status='Owner' where id=s.customer_id; update public.crm_leads set status='Sold' where id=s.lead_id; insert into public.crm_activities(activity_type,subject,status,customer_id,lead_id,stock_bike_id,sale_id,created_by) values('Note','Motorcycle delivered and sale completed','Completed',s.customer_id,s.lead_id,s.stock_bike_id,s.id,p_user_id); end $$;

do $$ declare t text; begin foreach t in array array['crm_payments','crm_invoices','crm_deliveries'] loop execute format('alter table public.%I enable row level security',t); execute format('drop policy if exists "Authenticated staff full access" on public.%I',t); execute format('create policy "Authenticated staff full access" on public.%I for all to authenticated using (public.crm_staff_can_access()) with check (public.crm_staff_can_access())',t); execute format('drop trigger if exists %I on public.%I','set_'||t||'_updated_at',t); execute format('create trigger %I before update on public.%I for each row execute function public.crm_set_updated_at()','set_'||t||'_updated_at',t); execute format('drop trigger if exists %I on public.%I','audit_'||t,t); execute format('create trigger %I after insert or update or delete on public.%I for each row execute function public.crm_audit_change()','audit_'||t,t); end loop; end $$;
